#+OPTIONS: toc:nil num:nil

#+BEGIN_HTML
---
layout: post
title: Self-driving cars and local economies
excerpt: What unintended economic impacts might self-driving cars have?
---
#+END_HTML

Over the past few days, I have been driving from Madison, WI to Fremont, CA--a journey of [[https://www.google.com/maps/dir/Madison,%2BWI/Fremont,%2BCA/@39.4094874,-123.7222639,4z/am%3Dt/data%3D!3m1!4b1!4m14!4m13!1m5!1m1!1s0x8806536d3a2019ff:0x4e0cfcb5ba484198!2m2!1d-89.4012302!2d43.0730517!1m5!1m1!1s0x808fbf46b7e8caf7:0x8ada313b89d888d4!2m2!1d-121.9885719!2d37.5482697!3e0][over 2,100 miles]]. I am writing this from a motel room near Reno, NV, though I will have finished my trip by the time this is published.

Most of the time, I have been driving on the I-80--a magnificent intercontinental highway that runs from New York to San Francisco. Along the route are many hotels, restaurants, gas stations, etc. that are highly dependent on the motorists and truck drivers that plod along this trail.

It is not an accident that today's highways closely follow yesteryear's railways, which themselves followed paths trod out by the wagons and carts. As modes of transportation have evolved, communities along the route have been forced to adapt to keep themselves relevant. Horse-changing stations for the Pony Express gave way to coal depots for locomotives, which have in turn given way to truck stops and gas stations.

As I drove along the highway, I couldn't help but think about the impact that self-driving vehicles could have on these communities.

A truck driver can drive 8-12 hours a day. A self-driving truck, which does not need to stop (except for fuel or maintenance), could complete a trip in one-half to one-third the time. This is a massive increase in efficiency, even excluding additional factors (mostly ones related to human "frailties", like eating, using the restroom, taking rest breaks, etc.).

What would happen to communities along the route if technology and law progressed to the point at which this was feasible?

Some of the communities would not survive. Without enough motorists and truck drivers to patronize their businesses, people would slowly leave.

Others, though, may benefit. It'll be all about location. If all trucks can avoid stopping until they need to fill up on gas, then a community that is located precisely one tankful from a major transport hub would get all the business. Once again, technology proves to be an instrument for concentrating wealth.

If the economic scenario holds true, the political implications would be even more interesting. One could imagine truck drivers lobbying against self-driving vehicles that would leave them out of a job--might restaurateurs, gas-station owners, etc. join them?

More broadly, the transportation industry is hugely important to the hinterland regions--surely there will be resistance to Silicon Valley (or Detroit, as the case may be) trying to capture all the value through technology?

By now, we have probably all seen (or at least read about) taxi drivers protesting against Uber. Relatively speaking, however, taxi drivers are a small group. If self-driving cars prove to be as disruptive a technology as the previous scenario lays out, we've got a much bigger social and political battle ahead of us.
