#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: Batteries, the next frontier
excerpt: No technological breakthrough would be as important as improved batteries
---
#+END_EXPORT

I recently purchased a 13-inch [[https://www.asus.com/us/Notebooks/ASUS-ZenBook-UX305FA/][ASUS UX305FA]] ultrabook. I've long had an [[https://www.asus.com/us/ROG-Republic-Of-Gamers/ROG-G75VX/][ASUS G75VX]], a 17-inch gaming laptop which also serves as a phenomenal workstation replacement, but I've become convinced that increased portability and battery life would increase the amount of work that I got done.

Occasionally, I find myself itching to write some code, but find that my laptop is not at my fingertips--or, if it /is/ available, low on power. On those occasions, I usually have a tablet, but mobile devices are much better suited for consumption than production.

On the portability front, the UX305 is fantastic. It weights only 2.5 lbs (1.2 kg), which is light enough to lift and carry with one hand. Without the charger, it's as easy to carry around as a thin binder.

Alas, the caveat here is "without the charger". Despite the advertised battery life of 10 hours, the laptop lasts only about 5 hours under my "regular usage".

Perhaps this is to be expected: an advertising trick, much like vehicle MPG, that we are expected to take with a grain of salt.

I'm not satisfied with this explanation, however. I remember the days when "dumb" phones could go three days with a single charge. Today's "smart" phones can barely last half a day without begging for juice.

It's clear that electronic devices are constrained by their batteries. This constraint is a "sharp" one, in the sense that incremental improvements in battery life will not ameliorate the problem of needing to carry a charger. If a device cannot last a whole day--8 to 16 hours of "regular usage"--users will need to carry a charger with them, regardless of whether the device lasts 3 hours, 5 hours, or 7 hours.

For many years, computer performance was limited by hard drive speed. No matter how much faster the processor got, or how much RAM was added, operating systems and applications did not get significantly faster due to slow disk-reading and writing speeds.

When solid-state drives (SSDs) came onto the market, their impact was immediate. Boot times and application start times fell dramatically, which made computers feel much faster.

What we need is a similar success story with batteries: a several-fold improvement in performance, not 10% or 20%.

The UX305 has a 45 Wh battery. "Real-world" performance is around 42 Wh. "Regular usage" results in a discharging rate of around 10.5 W. Thus, the laptop should last 4 hours. In order to last 8 hours, we'd need /two/ batteries--or a /doubling/ of capacity. A /tripling/ of capacity to 12 hours of usage would be ideal for a power user like me.

This is clearly not going to be accomplished through incremental improvements on existing technologies. Something brand new is needed. Intense effort is being devoted to battery technology R&D by the [[https://www.tesla.com/powerwall][private]] and [[http://www.telegraph.co.uk/business/2016/08/10/holy-grail-of-energy-policy-in-sight-as-battery-technology-smash/][public sectors]] alike, but we have yet to see revolutionary results.

From R&D to commercialization, I predict that it will be at least 5 years before we have a revolution in (consumer) batteries. Storage solutions for much larger amounts of energy--e.g. the power generated by solar farms and wind turbines--are further away still.

Perhaps we should be patient--after all, better batteries are not nearly as far out of reach as nuclear fusion. But as a technology enthusiast, I can hardly wait for the day when I can confidently leave the house with my laptop, without its charger, and return home with a still-powered device.
