#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: Coders at work
excerpt: Experiences of great programmers are enlightening
---
#+END_EXPORT

I've recently been reading Peter Seibel's [[http://www.apress.com/us/book/9781430219484][Coders at Work]], a collection of interviews with some of the best programmers alive today. Having enjoyed Seibel's [[http://www.gigamonkeys.com/book/][Practical Common Lisp]], I had high expectations for his work, and was not disappointed.

/Coders at Work/ is derived from hours of interviews with such luminaries as [[https://labs.oracle.com/pls/apex/f?p%3Dlabs:bio:0:120][Guy Steele]], [[http://joearms.github.io/][Joe Armstrong]], and [[https://www.microsoft.com/en-us/research/people/simonpj/][Simon Peyton Jones]]. Throughout these interviews, Seibel digs into issues such as how these great programmers got started, what they think of the field today, and where they think software development is going. Some interviews are more historical; others, more technical. The book is clearly intended for programmers, but (as interviews are wont to) takes a conversational tone.

A few takeaways from these interviews:

- Great programmers prefer to work alone
- Interest and dedication are more important than technical skill
- Industry tackles harder problems than academia, but has less leeway to pursue elegant solutions
- There's something of a split between those who want to get software up and running as quickly as possible and those who want to plan everything out

I've yet to finish the book, having jumped immediately to the interviewees that most interested me, such as [[https://www.jwz.org/about.html][Jamie Zawinski]] and [[http://norvig.com/][Peter Norvig]]. The book is long--over 600 pages--but is deeply engaging. I can't wait to get back to it, and I recommend it to anyone who wants to know more about the field and the men[fn:1] who defined it.

* Footnotes

[fn:1] All interviewees are indeed men
