#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: WiFi passwords--or, why Linux is a hassle
excerpt: Why must distros differ on unimportant things?
---
#+END_EXPORT

I recently had to reconnect to a wireless network that I have not connected to in a long time. Fortunately, though I had long forgotten the password, the computer still remembered it. Not wanting to find myself disconnected without knowing the password, I sought to look it up in the system.

A quick Google search indicated that [[http://askubuntu.com/a/139337][Ubuntu]] stores wireless passwords at =/etc/NetworkManager/system-connections=. It quickly became clear that this was /not/ where my Fedora system stores WiFi passwords: there are no files in the directory. This is surprising, since =NetworkManager= is a [[https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/ch-NetworkManager.html][RedHat product]].

Further investigation uncovered that Fedora stores WiFi passwords in the =/etc/sysconfig/network-scripts/= directory. I am /sure/ that there are is a good reason for this, but that's beside the point. Implementing the same basic functionality--storing WiFi passwords--differently in two Linux distros is just unnecessary complexity.

The difference, however, is not large enough to avoid a [[http://news.softpedia.com/news/All-Linux-Distributions-Store-Wi-Fi-Passwords-in-Plain-Text-If-You-Don-t-Use-Encryption-412387.shtml][major security issue]]: both distros store WiFi passwords in plain text files in under the =/etc= directory. Archlinux, which uses the =netctl= tool by default, is /somewhat/ more secure through the use of encryption, but still far from perfect.

And therein lies the rub: Linux distros, for whatever reason, insist on /different/, not /better/, ways of doing things. Until these /unnecessary/ differences are eliminated, the Linux community will find it difficult to make progress on important issues.
