#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: Tech is tyrannical
excerpt: Technology is not democratic--it is autocratic
---
#+END_EXPORT

The Greek philosopher Aristotle believed there were three types of government:

- One-man rule
  - Monarchy, tyranny
- Elite rule
  - Oligarchy, aristocracy
- Mass rule
  - Polity, democracy

Though Aristotle believed that polity[fn:1] was the preferable form of government, he observed that all three types were found throughout the Greek world, and so there was no objective superiority of one over the others.

Among technologists, it is widely believed that technology inherently empowers the individual and is destined to democratize societies. Given the history of various technologies, this belief is puzzling:

- Agriculture enlarged the role of men and diminished that of women
- Irrigation led to the rise of hydraulic civilizations ruled by god-kings
- The printing press undermined the authority of the Church--in favor of the State
- Radio/TV gave charismatic leaders unprecedented reach

A narrower argument is that certain /distributed/ technologies, most importantly the internet, have given individuals greater voice. This may be true in absolute terms, but influence is relative, and it's unclear that more people talking leads to greater public input.

Putting aside the fact that the internet is [[https://en.wikipedia.org/wiki/2008_submarine_cable_disruption][not nearly as "distributed"]] as many believe, the cacophony of communication today tends to drown out rather than promote ideas. Given that the vast majority of communication is trivial[fn:2], the loudest voices are invariably those of the best-known individuals and groups, resulting in an amplification of the few rather than the many.

In such an environment, /brand/ is the most important asset. Governments, companies, and individuals carefully cultivate their brands, painstakingly crafting an image of themselves that may not have any basis in reality. Branding is an exercise in output, not input--talk, don't listen. Social media may /seem/ interactive, but it need not be a two-way exchange. Facebook and Twitter are often used as broadcast platforms, no different from television, but superior in that they lead the audience to /believe/ they are actively participating.

When it comes to the companies that provide these technologies, only two things matter: integration and scale. In the same way that U.S. Steel was able to lower costs by controlling the whole supply chain, from mines to mills, Apples, Facebook and Google's goal is to get their users to use only their technologies, not those of their rivals. The more a user stays in "Google world", the better Google can control and "improve" their experience.

In this, American companies are not as far along as those in East Asia. In South Korea, [[https://www.theatlantic.com/business/archive/2012/07/whoa-samsung-is-responsible-for-20-of-south-koreas-economy/260552/][Samsung Group accounts for 20% of GDP]], and it is possible to live a wholly "Samsung life". In China, WeChat has its fingers in so many pies that it comprises the [[https://stratechery.com/2017/apples-china-problem/][entirety of millions of people's digital experience]]. Such "tech keiretsus" gain a nearly insurmountable advantage over rivals by dominating mindshare to such an extent that few even /think/ to consider an alternative service.

Where is all of this leading? I've no idea, but one thing's for sure--it does not seem to be the path of individual empowerment and democratization.

* Footnotes

[fn:1] Rather than its corrupted form, democracy

[fn:2] A glance at what's trending on Twitter at any given time should convince everyone of that
