#+OPTIONS: toc:nil num:nil

#+BEGIN_HTML
---
layout: post
title: RSI and the Kinesis
excerpt: Repetitive strain injury is no joke
---
#+END_HTML

A few weeks ago, I purchased a [[https://www.amazon.com/Kinesis-Advantage2-Ergonomic-Keyboard-KB600/dp/B01KR1C5PY][Kinesis Advantage II]] keyboard in an attempt to find a keyboard that could ward off repetitive strain injury (RSI).

I'd never paid RSI much thought until I started using Emacs for long periods of time each day. Although I did the usual things, such as remap =Caps Lock= to =Control=, it soon became clear that Emacs' keybindings are not designed to be ergonomic on a modern keyboard (or any keyboard, for that matter). After a few months, my wrists started feeling sore at the end of each workday, and for the first time I had to carefully "budget" the amount of time I spent in front of the keyboard, which inevitably meant less typing and coding during personal time.

Having realized that this RSI stuff is no joke, I swiftly shelled out the nearly $350 for the Kinesis Advantage II and began to practice typing it. It immediately became apparent that this wasn't something I was going to transition to easily. The bowl-shaped design, vertical key alignment, and rearranged keys all proved to be significant challenges to my muscle memory.

For the next few days, I spent more time remapping the modifiers keys to make them more conducive to using Emacs than I did practicing typing. After an awful lot of swapping keys back and forth, I put the keyboard down in frustration and didn't touch it for a month. After more weeks of sore wrists, however, I've picked the Kinesis up again and am slowly but surely getting better with it.

The biggest challenge for me with the Kinesis is to /unlearn/ all the bad habits I've developed with ordinary keyboards, particularly the exaggerated movements required to reach keys far from the home row. The Kinesis, it is obvious, is designed to minimize hand and finger movement, which I'm not used to.

It'll take a /long/ time before I'm as fast typing on the Kinesis as I am on, say, a laptop keyboard, but the long-term benefits are clear. I'll keep at it no matter how many typos I make.
