#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: Augmented reality
excerpt: A quick recap of where AR is at
---
#+END_EXPORT

I just went to an [[https://www.meetup.com/ARSFBA/events/236282556/][augmented reality meetup]] at the [[https://www.google.com/maps?f%3Dq&hl%3Den&q%3D301%2BHoward%2BStreet,%2BSan%2BFrancisco,%2BCA,%2B94105,%2BUS][Google Launchpad]] with [[https://www.collinchu.com/][a friend]]. A quick recap of the topics discussed and my own thoughts:

- Sivan Iram of [[https://lumusvision.com/][Lumus]] presented on waveguide technology for AR optics
  - Newest product is a dev kit (costing around $3,500 IIRC), which is a pair of glasses that can project 3D images
- Carter Agar of Lenovo presented on a headset-smartphone-controller combo that allows Jedi lightsaber duels in AR. Costs ~$200 and expected to come out December 2017 to tie in with the next Star Wars movie.
  - Based on success, will consider creating 2nd gen
  - High cost of device expected to be offset by strength of Star Wars brand
- Edward Tang of [[https://www.avegant.com/][Avegant]] joined in a panel discussion on the state of AR and the biggest challenges.
  - The biggest challenge in his view? Optics, of course, which is what Avegant tackles with lightfield technology.
- Stefano Baldassi of [[http://www.metavision.com/][Meta]] demonstrated an AR headset that allows the user to:
  - Drag items (e.g. a model of the human body) off a virtual shelf, enlarge it, rotate it, pull pieces apart, etc.

A few areas in which panelists were in agreement:

- Big tech companies will ship dedicated consumer AR devices by 2020
  - Apple recently announced [[https://developer.apple.com/arkit/][ARKit]] for iOS 11
  - Facebook, Amazon, etc. have announced intentions to pursue AR
- AR market from now until 2020, and likely beyond, will be mobile devices
  - Headsets don't and won't have sufficient consumer adoption; this problem is currently seen in VR as well
- We've yet to discover good AR / VR UIs
  - In early days, mobile UIs were slightly adapted desktop / laptop UIs. Similary, VR / AR UIs are basically mobile UIs right now.
- Within 10-15 years, AR headsets may replace smartphones as /primary/ devices.
  - Just as PCs continues to exist, smartphones will continue to exist, but be relegated to /secondary/ devices

A few thoughts / questions of my own:

- If major companies won't deliver flagship AR devices until 2020, there won't be a major hardware platform like the Oculus Rift or HTC Vive for VR for quite some time.
- How good is mobile AR?
  - Is it a means to get consumers interested in dedicated AR headsets?
  - Can it deliver experiences that make people excited about AR?
- If AR platforms remain fragmented for several years, how can fusing many sources of data together, which I see as the greatest potential of AR, be achieved?
