#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: Prediction vs. analysis
excerpt: Approaching the future with a crystal ball is the wrong approach
---
#+END_EXPORT

Since earliest history, mankind has wanted to know what the future holds. Entire civilizations have been built around the ruler's supposed ability to gain insight into future events. Many oracles, seers, and fortune tellers have made comfortable livings off of worried masses. Even today, "experts" are brought onto media programs with the expectation that their expertise allows them to "see" what the future holds, from the oil price to Chinese GDP.

Is it possible to predict the future? Yes, but only certain things, and only by following certain processes. What god-kings, oracles, and media experts have in common is that they readily make predictions[fn:1] without bothering to describe the processes by which they reached their conclusions. Since most issues are framed in a binary way, this gives them a 50% chance of getting it "right", which is pretty good considering that the task at hand is something as audacious as predicting the future.

Being as curious as anyone about what the future holds, I've long subscribed to [[http://www.stratfor.com/][Stratfor]], a "geopolitical intelligence firm" founded by George Friedman. What attracted me to Stratfor was not merely their predictions--anyone can make predictions--but their description of their model-based[fn:2] process. The model-based processes entails:

- Identifying constraints
- Paying attention to high-level events, not individuals
- Regularly reviewing past predictions against outcomes and updating the model using empirical results

This model-based process has given Stratfor remarkable insight into the future. "Be stupid" is George Friedman's motto, and by paying attention to the obvious, he's accurately predicted the return of a Russian threat, the economic problems that China has gotten into, and the sharp contrast that has arisen between stability in the western hemisphere and chaos in the eastern hemisphere.

Many Stratfor predictions have been off the mark--they failed to anticipate the rapid territorial expansion of ISIS, for example. Yet, such events often seem less significant in retrospect than they do in the moment. ISIS took over a lot of territory, but even at the height of its expansion was still landlocked and surrounded by enemies, and has been losing territory ever since. In other words, these events are simply not deemed as important by the predictive model as by the people living though them, which is perfectly reasonable.

George has since left to found rival [[https://geopoliticalfutures.com/][Geopolitical Futures]]. The quality of Stratfor publications has visibly declined since his departure, but the importance of the model-based process is greater than ever in an age of information overload.

* Footnotes

[fn:1] With enough caveats to salvage their reputations should the predictions not pan out, of course.

[fn:2] As opposed to source-based, which is Hollywood's typical portrayal of intelligence services
