#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: The Road to Cyber Serfdom
excerpt: Lack of property rights in cyberspace is creating dissatisfaction
---
#+END_EXPORT

The technology industry is under attack. While corporations have always been targets of regulations and lawsuits, what's happening today is notable due to the sheer number of /directions/ the attacks are coming from.

- President Donald Trump is attacking Amazon and its owner, Jeff Bezos, for [[https://twitter.com/realDonaldTrump/status/981168344924536832][taking advantage of low postal rates]] to compete unfairly against brick-and-mortar businesses.
- Bezos is also under attack for using The Washington Post--which he owns personally--to [[https://twitter.com/realDonaldTrump/status/981881669593559040][promote a personal political agenda]].
- Facebook is [[https://www.recode.net/2018/3/19/17140410/facebook-mark-zuckerberg-seecurity-data-50-million-users-cambridge-analytica-president-donald-trump][under fire]] from conservatives for censorship and liberals for not censoring enough
- [[http://fortune.com/2018/04/08/facebook-suspends-cubeyou-aggregateiq/][Data mining]], which is nothing new, has suddenly taken on political (if not geopolitical) importance
- YouTube's demonetization practices led a woman to [[http://www.foxnews.com/us/2018/04/03/gunshots-reported-at-youtube-headquarters-in-california.html][carry out a shooting]] at the company's headquarters

It's rare, perhaps unprecedented, for so many major tech companies to come under attack /simultaenously/ for such /different/ reasons. But perhaps the reasons so different after all?

All of these issues are the result of several basic factors:

- Digital activities are becoming increasingly more economically valuable
- The internet, unlike the physical world, does not have a sophisticated tradition of property rights
- Global(ist) corporations capture a large and increasing share of digital activity and consequent economic value

The internet, which in its early days was described as a "Wild West", increasingly resembles a feudal system.

- Massive corporations like Google and Facebook own the digital properties of any value[fn:1].
- Users don't /own/ their YouTube or Facebook pages--the corporation, like the feudal lord, has the right to revoke right of usage any time
- Value generated from these digital properties don't go directly to the creator, but to the corporation, which then distributes an arbitrary share--just as crops grown by serfs all go to the lord, who then attributes them a portion

When you message friends on Facebook, Facebook takes those messages and sells them. When you post content on YouTube, YouTube determines which of your videos are be monetized and for how much. Even the mere act of browsing the web leaves one vulnerable to being tracked /across sites/ with cookies[fn:2].

For the past millennium, Anglo-Saxon countries have enjoyed great peace and prosperity relative to others in large part due to a more equitable and sophisticated system of property rights[fn:3]. If we're to maintain that, America must lead the way in establishing digital property rights that benefit individuals and thus society as a whole.

* Footnotes

[fn:1] Unlike the physical world, digital properties have no inherent value--only human effort makes them attractive. While anyone can "strike out on their own" and create their own URL or app, few can turn those pages and programs into anything worth paying for.

[fn:2] Imagine the outrage if a company followed you in the physical world with a drone, recording your ever move. Yet companies use cookies to do the digital equivalent all the time.

[fn:3] Which really was the central focus of the Magna Carta and just about every political document that followed
