#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: Data Really IS the New Oil
excerpt: Similarities between two seemingly unrelated resources
---
#+END_EXPORT

Google proudly announced in 2017 that they're using [[https://environment.google/projects/announcement-100/][100% renewable energy]]. Facebook [[https://www.utilitydive.com/news/facebook-selects-100-renewable-energy-option-for-headquarters/505723/][swiftly followed]]. Ironic, then, that The Economist [[https://www.economist.com/news/leaders/21721656-data-economy-demands-new-approach-antitrust-rules-worlds-most-valuable-resource][likened them to oil companies]] the very same year, popularizing the idea that "data is the new oil". It's a comparison that probably made more than a few greens at the companies wince.

The Economist piece, though brief, touches on some important points: data, like oil, is a commodity; the goal is not merely possessing the resource, but to dominate the market and prevent /others/ from having it; and anti-trust regulations drafted in the early 20th Century are ill-equipped to deal with the way tech companies operate today.

But the comparison between data and oil goes beyond market share and trust-busting. It's an important means of understanding the /motivations/ and /behaviors/ of tech companies. Liberal politics and free lunches aside, Google's no different from Exxon Mobil, or Facebook from BP.

Take the issue of value generation, for example. One way in which data is similar to oil is that value increases with quantity. A small amount of data or a few barrels of oil has little value. As quantity increases, /emergent value/ is created from the ability to /influence the market/, whether by manipulating prices à la OPEC or controlling visibility of information à la Facebook.

Gathering large quantities of data, however, is considerably easier than producing large quantities of oil. This is only partly due to the digital vs. physical divide. Fundamentally, tech companies are able to gather lots of data quickly because /ownership rights are weaker for digital and physical property/[fn:1]. An oil company that wants to drill on your land has to approach you with a contract for a specified time period and offer royalties[fn:2]; a tech company only needs you to click through a ToS[fn:3] spy on you indefinitely.

Another parallel is in dealing with mistakes, some of which could be rightly called disasters. Sony's [[https://www.eurogamer.net/articles/2016-04-26-sony-admitted-the-great-psn-hack-five-years-ago-today][PSN hack]] comes to mind, as does the more recent [[https://www.consumer.ftc.gov/blog/2017/09/equifax-data-breach-what-do][Equifax data breach]]. In terms of impact on users, they're no better than the [[https://en.wikipedia.org/wiki/Deepwater_Horizon_oil_spill][Deepwater Horizon oil spill]]--perhaps worse, since personal and financial data were directly exposed to criminals. Facebook's recent scandal involving third-party apps siphoning data from the platform and (supposedly) using it to influence the 2016 elections, however, is Exhibit A in how tech companies stonewall, admit minimal responsibility, and move on as quickly as possible in exactly the same way that oil companies do.

The difference, however, is that tech companies get away with /much/ lighter punishments. BP was [[https://cfpub.epa.gov/compliance/criminal_prosecution/index.cfm?action=3&prosecution_summary_id=2468][fined billions of dollars]] in the wake of Deepwater Horizon, and CEO Tony Haywood was even [[https://www.youtube.com/watch?v=15HTd4Um1m4][lampooned by South Park]]. When Facebook CEO Mark Zuckerberg's testified before Congress, [[https://www.cbsnews.com/news/mark-zuckerberg-testimony-reveals-congress-confusion-about-facebook/][mainstream media]] focused its attention on Congressmen's lack of understanding of how Facebook works[fn:4], and no punishment has been (or, I predict, will be) levied. Swiftly after returning to Menlo Park, Zuckerberg was greeted with news that Facebook's revenue had [[https://www.wsj.com/articles/facebook-reports-higher-revenue-earnings-1524687694][increased 50% yoy]].

In short, data /is/ the new oil, and tech companies are the new oil conglomerates. The main difference is that the public has less ownership over their data than over the minerals beneath their feet, and tech companies get away with more than oil companies dare dream of. Don't be misled by Silicon Valley's moralizing; it's as hollow as an empty oil drum.

* Footnotes

[fn:1] See [[http://www.tianxiangxiong.com/2018/04/08/the-road-to-cyber-serfdom.html][The Road to Cyber Serfdom]] for more

[fn:2] The US is one of very few countries in the world with individual mineral rights; even other English-speaking countries, like UK and Australia, do not.

[fn:3] Many companies go even further, using the ToS as a "foot in the door" to track you even when you're not using their service. Some unscrupulous ones even ransack your device. The things you come to know when working in the tech industry...

[fn:4] By the way, many researchers and industry professionals would also /love/ to know
