#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: The Strange Obsession With 5G
excerpt: Beware technology that becomes a symbol of everything else
---
#+END_EXPORT

There's a strange obsession with [[https://en.wikipedia.org/wiki/5G][5G]] these days that, as far as I can tell, has little to do with the technology itself. The US is [[https://www.cnet.com/news/huawei-ban-full-timeline-on-how-and-why-its-phones-are-under-fire/][banning]] not only Huawei 5G equipment but preventing US companies from supplying components to the Chinese company. Secretary of State Pompeo has [[https://www.nytimes.com/2019/05/08/technology/pompeo-huawei-britain.html][warned the UK]] in no uncertain terms that allowing Huawei to build their 5G network would bring about the end of Britain's participation in [[https://en.wikipedia.org/wiki/Five_Eyes][Five Eyes]]. This all seems quite sudden and extreme.

First of all, what is 5G? It's a new standard for wireless communication that uses [[https://www.lifewire.com/5g-spectrum-frequencies-4579825][higher-frequency signals]]. Such standards tend to be very complex, especially as corporations (or even gov'ts) have tremendous incentive to bend the standard their way to give themselves an advantage. The physics, however, is simple enough: the speed with which information can be transmitted over an electromagnetic wave is directly proportional to the wave's frequency; higher frequency, faster information transmission. The tradeoff[fn:1] is that higher-frequency waves are more easily absorbed by trees, buildings, and even the air itself, so range is dramatically decreased and more radio transmitters are needed.

So what's the big deal? Sure, it's nice to stream video faster on the phone, but how did this suddenly become a national security issue? Even if [[https://www.youtube.com/watch?v=faLH3crTnfE][robots can be more smoothly controlled]], is it really so serious that the Secretary of State must get involved?

First, the espionage issue should be treated separately from the 5G issue. The sticking point there is over Chinese involvement in British telecom networks, not the particular technology. The nature of communication (or really anything IT) is that if an outside party gets access to any part of the chain, they could compromise the entire system. So it's no wonder the US is determined to make sure Five Eyes maintains communication integrity by keeping Chinese equipment out.

But that still doesn't explain the focus on 5G itself. While companies are eager to promise all sorts of technological revolutions stemming from 5G, from internet of things (itself an old canard[fn:2]) to self-driving cars (which /may/ come sooner than nuclear fusion), I've a few theories as to why 5G has suddenly become a hot topic:

1. The media's [[https://www.youtube.com/watch?v=CEQTo9usai4][obsession with horse races]], especially ones where the US seems to be lagging.
   - See: [[https://www.youtube.com/watch?v=zUTmKiKHVOM][Sputnik]], Japan's[fn:3] [[https://en.wikipedia.org/wiki/Fifth_generation_computer][Fifth Generation Computer]].
2. The defense establishment's eagerness to create a narrative of American vulnerability to secure--what else--funding.
   - Any buzzword senators don't understand would do, and 5G's as good as any other.
3. The lack of real results from 5G deployment[fn:4], which allows the narrative of revolutionary technological change to be maintained.
   - Years from now, when the real, mundane results are clear, we'll have moved on to another tech buzzword

All this is to say that 5G has become much more than a technology: it's a symbol of everything from our dreams of technological utopia to fears over US-China competition[fn:5]. And if there's one rule we should observe about technology, it's this:

#+BEGIN_QUOTE
When a technology ceases to be evaluated on its own merits and instead becomes a symbol of everything else, run the other way.
#+END_QUOTE

* Footnotes

[fn:1] In engineering, there are /always/ tradeoffs.

[fn:2] Beyond talking microwaves and $100 lightbulbs, IoT has found genuine value in domains like oilfield monitoring, but that never seems to be what its advocates, well, advocate.

[fn:3] Anyone interested in US-China relations, particularly topics like industrial espionage, should read Michael Crichton's [[https://en.wikipedia.org/wiki/Rising_Sun_(novel)][Rising Sun]], mentally replacing every instance of "Japan" with "China".

[fn:4] 5G is slowly rolling out in places like [[https://www.cnet.com/news/verizon-5g-map-network-now-live-in-chicago-and-minneapolis-limited/][Chicago and Minneapolis]], but the immediate performance improvement over 4G is dubious, and limited range is a significant drawback.

[fn:5] Personally, I find the US-China rivalry narrative hugely overblown. Geopolitical analyst Peter Zeihan [[https://annual.cfainstitute.org/2019/05/16/a-painful-realignment-peter-zeihan-on-brexit-fallout/chin][sums it up]] better than I could.
