#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: The end of PC corporatism
excerpt: Cultural and economic changes are coming simultaneously
---
#+END_EXPORT

It's often been said after the Cold War that the left won on the cultural issues and the right on the economic ones. The normalization of rock and roll ([[http://religiondispatches.org/the-devils-music-how-christians-inspired-condemned-and-embraced-rock-n-roll/][devil's music]]), for example, was a win for the left, while deregulation and [[https://www.cbsnews.com/news/union-membership-declined-in-2018/][de-unionization]], especially [[https://www.politico.com/story/2017/08/05/reagan-fires-11-000-striking-air-traffic-controllers-aug-5-1981-241252][during the Reagan years]], is touted as a triumph for the right. If so, both victories seem to have come full circle, corrupted by their own successes into imminent defeat.

On the left, too many contradictions in PC culture have accumulated. The interests of illegal aliens run directly counter to those of unions, while Islam and gays certainly don't see eye-to-eye. Biological males participating in women's sports--and inevitably winning--has [[https://people.com/sports/usa-powerlifters-vote-transgender-competitors-ban/][spawned an angry backlash]], with none more outraged than female athletes deprived of their rightful victories. The "big tent" has grown too large and unstable, threatening to [[https://www.wsj.com/articles/democrats-smear-democrats-11563232018][collapse in on itself]].

On the right, globalist corporations are making a mockery of the free market. The biggest such companies can headquarter themselves in Ireland, manufacture in China, assemble in Mexico, and sell in the United States, taking advantage of every possible tax benefit, subsidy, and political arbitrage. Amazon, perhaps the worst offender, paid [[https://www.cnbc.com/2019/04/03/why-amazon-paid-no-federal-income-tax.html][no federal income tax in 2018]], instead receiving a rebate of hundreds of millions of dollars[fn:1].

As both the left's position on cultural issues and the right's position on economic ones become increasingly untenable, shoots of opposition have begun to arise. The Pulse nightclub shooting, in which a jihadi gunman targeted a gay club[fn:2], has been [[https://www.youtube.com/watch?v=xcbrc7Ugc6Y][cited by gays as a "wake-up call"]].  Conservatives, angry at [[https://thefederalist.com/2019/06/19/heres-conservatives-can-defeat-big-tech-censorship/][perceived suppression]] by tech companies, are leading the charge for [[https://www.theverge.com/2019/7/24/20726371/facebook-ftc-antitrust-earnings-q2-2019-privacy-regulation-mark-zuckerberg][antitrust action]].

Such pushback, however, is still in its early days, evidenced by the fact that it's mostly within the existing cultural and economic framework.

Rather than try to overthrow capitalism, most leftists are pushing for corporations to tackle economic issues such as the housing shortage. Google recently announced it would [[https://sf.curbed.com/2019/6/18/18683888/google-homes-amount-construction-homes-billion-housing-tech][donate land to build 20,000 homes]] over the next decade. This comes on the heels of Microsoft's announcement that it would [[https://www.cnet.com/news/microsoft-pledges-500m-to-build-homes-in-seattle/][pledge $500 million]] to build low-income housing in Seattle.

Instead of changing their [[http://www.tianxiangxiong.com/2018/04/08/the-road-to-cyber-serfdom.html][ideas about data and intellectual property]], most conservatives are (dubiously) citing First Amendment rights on platforms like Twitter, in many cases only reluctantly concluding that regulation is necessary (the "I'm a free market guy but..." argument).

Such feeble efforts are doomed to fail, as they don't understand, let alone address, the underlying issues of identity and monopoly. We should, therefore, expect more radical approaches to emerge as attempts to reform the PC corporatist system from within stumble.

* Footnotes

[fn:1] Amazon's selection process for its HQ2, which saw cities across North America compete for the [[https://www.citylab.com/equity/2018/05/the-hypocrisy-of-amazons-hq2-process/560072/][privilege of giving the company benefits]], is the most naked display of corporate power I've ever seen.

[fn:2] The media ran cover for the Islamic terrorist, [[https://www.telegraph.co.uk/news/2016/06/14/orlando-gunman-was-a-regular-at-lgbt-nightclub-pulse-before-atta/][irresponsibly speculating]] that he was a closeted gay. This is [[https://www.thestranger.com/slog/2018/04/05/26009169/trial-reveals-the-pulse-shooting-wasnt-about-homophobia-it-was-about-us-foreign-policy][refuted by the gunman himself]].
