#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: The decline of black political power
excerpt: Co-option by others and arithmetic reality demand a different stratgy
---
#+END_EXPORT

[[https://www.voanews.com/usa/race-america/hundreds-domestic-terrorism-investigations-opened-start-george-floyd-protests][Protests and riots]] in the aftermath of George Floyd's death have made "Black Lives Matter" a widely-known public slogan. [[https://www.nytimes.com/2020/06/02/arts/music/what-blackout-tuesday.html][Social media campaigns]] quickly arose for people to "show solidarity"[fn:1], while corporate wallets were [[https://www.cnet.com/how-to/companies-donating-black-lives-matter/][swiftly opened]] both to preempt criticism and take advantage of an advertising opportunity. It seemed for a moment that racial grievances over police encounters, which first caught national headlines during the [[https://www.stltoday.com/news/local/metro/memorials-protests-in-ferguson-on-the-sixth-anniversary-of-michael-browns-death/article_7a86a9be-220f-5279-a758-81fec3f029f8.html][2014 Ferguson Riots]] and was amplified by former NFL player Colin Kaepernick's decision to [[https://theundefeated.com/features/a-timeline-of-events-since-colin-kaepernicks-national-anthem-protest/][kneel during the national anthem]] in 2016, had finally reached a critical mass that would catapult the "modern civil rights movement" to success.

Closer inspection, however, reveals large cracks in this narrative. A [[https://www.pewresearch.org/fact-tank/2020/06/24/recent-protest-attendees-are-more-racially-and-ethnically-diverse-younger-than-americans-overall/][Pew Research survey]] showed that only 17% of protesters were black--fewer than the 22% who were Hispanic. Both combined are less than the 46% who were white. Some of the most violent rioting are in [[https://www.cbsnews.com/news/riot-declared-portland-second-night/][Portland]], a city that's only [[https://www.census.gov/quickfacts/fact/table/portlandcityoregon/BZA115218][5.8% black]], and Seattle, which is [[https://www.census.gov/quickfacts/fact/table/seattlecitywashington,US/SBO050212][7% black]], compared to 13% nationally. Rioters are [[https://katu.com/news/local/police-identify-26-arrested-in-overnight-portland-unrest][overwhelmingly young white]] "Antifa" whose actions, like [[https://catholicvoiceomaha.com/st-junipero-serra-statue-torn-down-in-san-francisco-park/][tearing down statues of Catholic saints]], are orthogonal to any black causes. No wonder, then, that many black protesters feel that Black Lives Matter's agenda [[https://www.nbcnews.com/news/nbcblk/black-people-portland-struggle-be-heard-amid-protests-n1236275][has been co-opted]].

But what /is/ the BLM agenda? While surely any decent human being believes that "black lives matter" in the general sense, movements are spearheaded by specific organizations. The official Black Lives Matter group has a [[https://blacklivesmatter.com/what-we-believe/][laundry list of positions]], only a minority of which have anything to do with blacks. From defending transgender rights to fighting ageism to breaking up the nuclear family, Black Lives Matter is a vector for a hodgepodge of ideologies that more generally mirrors the Democratic platform than any black-specific interests. In fact, fundraising for the organization is [[https://abc6onyourside.com/news/nation-world/as-black-lives-matter-donations-surge-some-want-to-know-where-the-money-goes][processed through ActBlue]], the same organization in charge of bringing in money for the Democratic Party, leading to serious questions as to where the donations are going. This only adds to the belief that the movement has been co-opted by political operatives during an election year.

Many of these agenda items aren't just irrelevant to blacks but wholly against black opinion. The black population is [[https://www.politico.com/story/2019/05/15/pete-buttigieg-black-voters-1322396][less comfortable with homosexuality]] than average, yet the organization, [[https://oloc.org/black-lives-matter/][founded by 3 lesbians]], puts LGBT causes front-and-center. Protesters have called to defund police departments in major cities, but blacks politicians have [[https://www.nytimes.com/2020/08/10/nyregion/defund-police-nyc-council.html][voiced opposition]] to what they see as a surefire path to more crime in their neighborhoods--and [[https://www.vox.com/2020/8/3/21334149/murders-crime-shootings-2020-coronavirus-pandemic][data is proving them right]]. The media coverage of Black Lives Matter seems almost designed to drown out the [[https://www.foxnews.com/media/11-year-old-gun-violence-washington-july-fourth-crime][views of black people]] impacted by its policies.

Dissonance between those claiming to represent black interests and the actual black population has resulted in the movement's descent into chaos and confusion. Protests have turned into looting in [[file+sys:][New York]], [[https://www.newsweek.com/what-happened-chicago-looting-protests-police-1524053][Chicago]] and elsewhere, while grandiose demands like abolishing police have fizzled into [[https://thehill.com/homenews/state-watch/511429-seattle-city-council-approves-cutting-100-police-positions-1-percent-of][1% budget cuts]]. Technologies that would better target criminals and therefore improve police-civilian interaction, like security cameras and facial recognition, have been [[https://t.co/TcsUXTnja4?amp=1][restricted]] or [[https://www.nytimes.com/2019/05/14/us/facial-recognition-ban-san-francisco.html][banned]]. Without precision tools, police departments have to either resort to blunter instruments like racial profiling, which worsens community relations, or give up entirely, which abandons neighborhoods to criminal terror.

The only sure outcome of all this appears to be that black lives won't be improved[fn:2]. That's a stunning conclusion for a movement called Black Lives Matter, but it reflects a trend that's been ongoing for years--black political power is in steep decline. At 18%, Hispanics are a larger share of the population than blacks, and both Hispanic and Asian populations are [[https://www.nbclosangeles.com/news/national-international/asian-americans-growing-faster-than-any-other-group-in-the-us/1994686/][growing more quickly]]. Politicians have known this since [[https://www.mercurynews.com/2008/01/29/divisive-democratic-campaigners-try-to-turn-latinos-against-blacks/][over a decade ago]], which is why they've switched from "black" to "people of color" in their verbiage, while [[https://abcnews.go.com/Politics/joe-bidens-comments-diversity-black-community-worry-blunders/story?id=72246145][their thinking]] is even further along. When [[https://www.mic.com/articles/159402/here-s-a-break-down-of-how-african-americans-voted-in-the-2016-election][88% of the black vote]] couldn't deliver Clinton victory in 2016, it's only logical for the party to focus on cultivating new voting blocs. Keeping blacks on-side with rhetoric that masks a totally different agenda is just part of the game.

A growing number of [[https://www.newsweek.com/darrell-scott-calls-donald-trump-most-pro-black-president-1505906][black leaders]] and even [[https://www.kdrv.com/content/national/480873781.html][celebrities]] are realizing that advancing black interests requires making politicians work for their support rather than giving nearly all of it for free to a single party. These individuals were instrumental in [[https://theweek.com/articles/809828/why-trump-suddenly-supporting-criminal-justice-reform][getting President Trump on board]] with 2018's First Step Act, a significant piece of criminal reform legislation. By ensuring that their support isn't taken for granted, black [[https://blexitfoundation.org/][citizens]] and [[https://www.foxnews.com/media/vernon-jones-outrageous-question-msnbc-host-on-whether-not-paid-support-president-trump][representatives]] stand a better chance of making their votes count and avoid being co-opted. While the electoral arithmetic is real, arresting the decline of black political power is possible via smarter political engagement and exercise of the ballot.

* Footnotes

[fn:1] Social media campaigns are no doubt popular because they allow people to feel like they've contributed to something while doing nothing at all

[fn:2] And will likely be worsened by the destruction wrought by rioting and looting, as well as less engagement by law enforcement in their neighborhoods
