#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: Coronavirus and Globalism
excerpt: The retrenchment of globalism accelerates
---
#+END_EXPORT

The Wuhan Coronavirus epidemic that started in China's Hubei province early this year has made its way across Europe and the United States. Countries that seemed to dodge the crisis, like Turkey, are now seeing a [[https://www.dailysabah.com/turkey/coronavirus-cases-in-turkey-surpass-9000-with-131-dead/news][dramatic pick up]] in cases, indicating that their outbreaks have merely been delayed.

As the disease has far from run its course, debates over its danger, mortality rates etc. are quite meaningless. But its economic impact has already been felt sharply in China, which posted [[https://www.bloomberg.com/news/articles/2020-03-02/asian-factories-slammed-as-virus-sends-china-s-pmi-to-record-low][record low PMIs]] in Feb., and will no doubt decimate Europe and US as well in March and beyond. The business casualties are a lot [[https://www.bloomberg.com/news/articles/2020-03-27/stacks-of-urns-in-wuhan-prompt-new-questions-of-virus-s-toll][clearer than the human ones]], with the US launching a massive [[https://www.cnn.com/2020/03/29/politics/treasury-secretary-steve-mnuchin-stimulus-checks/index.html][$2.2 trillion stimulus]] with [[https://www.nbcnews.com/politics/congress/white-house-senate-reach-deal-massive-2-trillion-coronavirus-spending-n1168136][nary a peep of opposition]] from Congress, Germany readying [[https://www.bloomberg.com/news/articles/2020-03-25/germany-closes-in-on-historic-bailout-to-counter-virus-blow][€750 billion]] in government spending and loan guarantees, and China [[https://www.reuters.com/article/us-health-coronavirus-china-toll/china-readies-stimulus-measures-as-local-virus-cases-dwindle-idUSKBN21F00F][cutting deposit rates and boosting lending]] to help businesses suffering not only from the virus-related shutdown, but also [[https://www.bloomberg.com/news/articles/2020-03-26/the-second-virus-shockwave-is-hitting-china-s-factories-already][canceled orders]] from hard-hit Western retailers[fn:1].

This raises a very important question: how did we get here?

The first question is one of origin. Doctors began noticing unusual cases of pneumonia in Wuhan in [[https://www.businessinsider.com/wuhan-doctor-chinese-sounded-alarm-coronavirus-outbreak-december-2020-3][December 2019]], but were censored by a local government obsessed with stability and avoiding public panic. This gave the virus time to spread across the city, leading to a surge in cases and [[https://www.washingtonpost.com/opinions/2020/03/26/my-hometown-showed-us-how-pandemic-begins-could-it-also-show-us-how-one-ends/][shutdown of major roads]] leading in and out of the city on Jan. 23. By January 30 the [[https://www.cnn.com/2020/01/30/health/coronavirus-illinois-person-to-person-cdc/index.html][first human-to-human transmission]] was found in the US, leading to a declaration on health emergency and [[https://www.mercurynews.com/2020/01/31/us-declares-health-emergency-bans-most-travelers-from-china/][flight ban from China]] the day after[fn:2]. China has since sought to avoid responsibility for spreading the virus by claiming it [[https://www.wsj.com/articles/canadian-writer-fuels-china-u-s-tiff-over-coronaviruss-origins-11585232018][originated in the US]] or [[https://qz.com/1823417/italy-now-key-to-china-coronavirus-origin-propaganda-efforts/][Italy]].

The second question is one of transmission. With the US having shut down China flights, the virus first burst onto the scene in Europe, spreading quickly across Italy, France, and Spain before making its way across the Atlantic to New York, the main port of entry for EU flights. This happened with astonishing speed: Europe decimated in two weeks and NY becoming the American epicenter within a month of China's national lockdown.

The pace of the virus' spread reflects the world's degree of globalization. That a virus out of central China can be killing New Yorkers within 2 months would likely come as a shock to many, yet even that's a better scenario than what could have happened without a timely China travel ban. With so much movement of people all the time, it's inevitable that something occurring in one part of the world swiftly spreads to another. This is not dissimilar to the financial contagion of 2008, where investment bank failures in New York quickly led to millions of factory workers being laid off in Guangdong. National borders are like compartment dividers on a ship; when they are removed, the whole thing can sink from a single leak.

Another of globalization's weaknesses on full display is the fragility of supply chains, as China makes most of the world's masks, ventilators, and drugs, which state media have [[https://www.foxnews.com/world/chinese-deny-americans-coronavirus-drugs][threatened to withhold]] from the United States. President Trump [[https://thehill.com/business-a-lobbying/business-a-lobbying/489948-trump-bucks-business-on-defense-production-act][invoked the Defense Production Act]], forcing GM to make ventilators after the automaker wanted to charge top dollar. Meanwhile, Tom Cotton, senator from Arkansas, introduced a [[https://www.cotton.senate.gov/?p=press_release&id=1342][bill]] to end US dependence on China-made drugs. Other countries like [[https://www.reuters.com/article/health-coronavirus-japan-autos/now-made-in-mexico-japan-auto-suppliers-shift-china-production-after-coronavirus-idUSL5N2AR0HF][Japan]] are also rushing to reduce their reliance on Chinese manufacturing, continuing a trend that started even before the epidemic with Trump's imposition of tariffs.

The virus, in short, has accelerated the retrenchment of globalization that started well before it. From travel bans to supply chain relocation to mutual recrimination between the US and China, it has thrown into sharp relief the weaknesses of the existing global system and quickened efforts for change. In that sense, it is a fitting event for our time.

* Footnotes

[fn:1] Other countries that have only started their shutdowns, like [[https://www.nytimes.com/2020/03/29/world/asia/coronavirus-india-migrants.html][India]], will inevitably need to reckon with the financial consequences as well.

[fn:2] Trump's decision was much criticized by the [[https://www.statnews.com/2020/01/31/as-far-right-calls-for-china-travel-ban-health-experts-warn-coronavirus-response-would-suffer/][media]], the [[https://www.cnn.com/travel/article/coronavirus-us-travel-restrictions-monday/index.html][Chinese government]], and [[https://www.foxnews.com/politics/house-pulls-bill-that-would-rescind-travel-ban-amid-coronavirus-outbreak][Democrat politicians]] at the time. None have apologized since.
