#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: The Sino-Russian delusion
excerpt: We need to focus on real threats rather than imagined ones
---
#+END_EXPORT

This July 4th, I originally wanted to write a piece about /How Americans Think/, but realized that, though I'd been chewing on it for some time, such a broad topic requires a lot more [[https://www.youtube.com/watch?v=f84n5oFoZBc&ab_channel=ClojureTV][hammock time]] to manifest. So instead, as a cheerful substitute, I'll write about one aspect of it--the American neurosis, specifically as applied to perception of a Sino-Russian threat.

** Our real national past-time

Americans love complaining. From the [[https://slate.com/business/2013/03/great-twinkie-shortage-of-2013-will-be-over-soon.html][Great Twinkie Shortage of 2013]] to [[https://www.americamagazine.org/politics-society/2019/11/05/american-empire-decline-and-were-not-ready-what-comes-next?gclid=Cj0KCQjwn4qWBhCvARIsAFNAMihqtw7tEYizB9XLHpf1h-36uHxZRgNLzQoRbIZmAE9pjTAUF4-d-FQaAjVdEALw_wcB][national decline]][fn:1](for the Nth time[fn:2]), there's no bad opinion that doesn't make it to the news. Part of this is due to the nature of American media, which derives what little revenue it can still get mostly from outrage[fn:3]. Among the self-styled intellectual elite who contemplate matters more important than snack cakes, however, few topics evoke more Serious Discussions of Utmost Seriousness™ than the Sino-Russian question.

Russia's February invasion of Ukraine, though [[https://www.youtube.com/watch?v=rkuhWA9GdCo&ab_channel=Speakers%27Spotlight][long predicted]] by perspicacious analysts, has significantly increased the amount [[https://www.cfr.org/blog/ukraine-war-china-and-taiwan][hand-wringing]] r.e. the China threat. For years there has been a worry about a [[https://www.bloomberg.com/news/articles/2022-06-14/why-increasing-russia-china-ties-worry-democracies-quicktake][Sino-Russian alliance]], an "[[https://www.reuters.com/world/china/moscow-beijing-partnership-has-no-limits-2022-02-04/][no limits]] partnership" between two autocracies, because it might force the US into fighting a [[https://www.airforcemag.com/kendall-unrealistic-for-air-force-to-fight-two-wars-while-modernizing/][two-front war it's not ready for]]. Any sign of closeness between Russia and China, therefore, sends American think-tankers into hyperventilation.

Given that both countries have rising tensions with the West, as well as a seemingly compatible economic relationship where Russia is a large commodities producer and China a large consumer, is a new Sino-Russian alliance in the offing? And if so, what kind of partnership might it be?

** The two-front war

The fear of states that two of their enemies should act in coordination is as old as time. From the 13th to 18th centuries Scotland and France had an [[https://www.bbc.co.uk/scotland/history/articles/auld_alliance/][alliance]] against England, leading to the latter's paranoia about a simultaneous invasion from north and south. In 1889, Britain's [[https://portsmouthdockyard.org.uk/timeline/details/1889-the-two-power-standard#:~:text=The%20Naval%20Defence%20Act%20is,shape%20naval%20policy%20until%201921.][Naval Defence Act]] established the principle that the Royal Navy should be as strong as any other two navies combined--a standard the US has since adopted. In 1905, Germany designed the [[https://www.britannica.com/event/Schlieffen-Plan][Schlieffen Plan]] to deal with the threat of France from the west and Russia from the east. The plan failed in the first stage--defeating France--in WWI, was revived for WWII and employed with great success, only to fail again in the second stage of defeating Russia. Clearly, the preparation for a two-front war consumes enormous resources, while the execution is extremely high risk. The Americans, who did win a two-front war with Germany and Japan, are of the opinion that it is something to be avoided at all cost.

The particular fear of a Russia-China alliance isn't new either. After the Nationalists were defeated during the Chinese Civil War, Americans agonized over the question of "[[https://www.trumanlibrary.gov/education/presidential-inquiries/who-lost-china][Who Lost China?]]"--not because the Truman administration had great sympathy for Chiang Kai-Shek, but because it understood that the US now faced the prospect of not only confronting the USSR in a devastated (and half-Soviet occupied) Europe, but simultaneously a hostile China in Asia. That fear would come true shortly thereafter in the Korean War, where General Douglas MacArthur was of the opinion that crossing the Yalu River and overthrowing the newly established Communists was the best option, only to be [[https://en.wikipedia.org/wiki/Relief_of_Douglas_MacArthur][relieved of duty]] for thinking long-term.

While a two-front war with Russia and China remains the nightmare scenario for US policy makers, a number of factors, from the historical to economic, makes this unlikely. In the following sections, we explore why.

** A history of conflict

The first significant political contact between Russia and China didn't take place until the 17th century, when Russia expanded into Siberia. Initially, the Qing Dynasty was able to hold its own militarily, leading to territorial demarcations such as the 1689 [[https://en.wikipedia.org/wiki/Treaty_of_Nerchinsk][Treaty of Nerchinsk]] that mostly kept Russia out of Manchuria. By the 19th century, however, Qing power was in steep decline eventually resulting in the [[https://en.wikipedia.org/wiki/Treaty_of_Aigun][wholesale]] [[https://en.wikipedia.org/wiki/Convention_of_Peking][loss]] of what the Chinese still call "Outer Manchuria", depriving China of access to the Sea of Japan.

In 1911, when the Xinhai Revolution began the process of dismantling the Qing Dynasty, Russia supported [[https://en.wikipedia.org/wiki/Mongolian_Revolution_of_1911][Mongolian independence]], resulting in the creation of a large buffer state between itself and China. In 1944, in the midst of WWII, the Soviet Union backed Uyghur separatists in the [[https://en.wikipedia.org/wiki/Ili_Rebellion][Ili Rebellion]], relenting only in 1949 when the Communists won the civil war and demanded that Moscow preserve China's territorial integrity.

While there was a period of partnership between the Soviet and Chinese Communists starting in the 1920's, due primarily to the latter's need for material support against the more numerous and better-equipped Nationalists, the relationship [[https://en.wikipedia.org/wiki/Sino-Soviet_split][imploded the 1960's]] and even came to blows in the 1969 [[https://en.wikipedia.org/wiki/Sino-Soviet_border_conflict#Battle_of_Zhenbao_(Damansky)_Island][Zhenbao Island Incident]].

Many reasons are given for the Sino-Soviet Split, from the personal to the ideological, but the fundamental cause is that large countries are never comfortable in a "partnership of equals"[fn:4]. While by the 1960's China thought itself co-leader of the Communist world alongside the Soviet Union, especially since Mao was a generation senior to Khrushchev, the USSR continued to view China as the junior partner, demanding to establish [[https://www.thecrimson.com/article/1966/7/22/ideology-is-not-cause-of-sino-soviet/][joint bases on Chinese territory]], leading Beijing to accuse Moscow of seeking to control Chinese development.

In the 1970's, as the Americans found themselves caught simultaneously in stagflation and Vietnam, Washington finally capitalized on the divisions between the two, dispatching [[https://nsarchive2.gwu.edu/NSAEBB/NSAEBB66/][Kissinger to Beijing]] and flipping China into the Western camp. This switch in the global power balance, much more than the Soviet war in Afghanistan or Reagan's defense buildup, is what brought about detente, Soviet attempts at economic reform, and ultimately the collapse of the USSR.

What is the point of recounting all this history? While Americans are forward looking in diplomacy, the CCP is always keen to bring up selective history to reinforce its claim to legitimacy[fn:5]. The Treaty of Aigun and conflict on Zhenbao Island are taught in every Chinese high school history textbook. When then-General Secretary Jiang Zemin finalized a [[https://www.latimes.com/archives/la-xpm-1994-09-04-mn-34898-story.html][border deal with Russia]] in the early 90's, he faced significant criticism for signing yet another "unequal treaty" despite the terms being broadly favorable to China[fn:6].

The history between Russia and China[fn:7] is rife with mistrust and conflict. While Beijing isn't emphasizing territorial disputes today, its relationship with its northern neighbor is an uneasy one. Russia, for its part, has no desire to be [[https://warsawinstitute.org/russia-chinas-junior-partner/][China's junior partner]] and [[https://www.reuters.com/world/europe/russia-arrests-scientist-alleged-collaboration-with-chinese-secret-services-2022-07-01/][reacts aggressively]] to Chinese espionage. Though there is a shared sense of being squeezed by the United States, the *two have mostly acted in parallel rather than in concert*, cooperating on small matters such as [[https://www.reuters.com/article/us-syria-security-un/russia-china-veto-u-n-approval-of-aid-deliveries-to-syria-from-turkey-idUSKBN24834N][UN votes]] and cultivating separate relationships with US foes such as Iran. History shows that these two countries will keep each other at arms' length, whatever the rhetoric--a fact we should not ignore in the face of bombastic political proclamations.

** Much ado about natural gas

When it comes to the economic relationship, much is made of the fact that Russia produces commodities while China consumes them. There is some truth to that, but as always media blows facts out of proportion.

In 2020 China was only Russia's [[https://unchartedterritories.tomaspueyo.com/p/why-germany-wont-keep-its-nuclear][9th largest natural gas consumer]], behind the likes of Hungary. The newly proposed [[https://www.pipeline-journal.net/news/power-siberia-2-pipeline-puts-ever-more-pressure-europe][Power of Siberia 2]] pipeline, if built, would increase export volumes by 10 bcm / year. To put that into perspective, the EU imported [[https://www.energymonitor.ai/policy/how-can-the-eu-end-its-dependence-on-russian-gas#:~:text=The%20EU%20imported%20approximately%20155,rising%20to%2065%25%20in%20Germany.][155 bcm of Russian gas]] in 2021. Moreover, the gas going to China and the EU are sourced from different [[https://en.wikipedia.org/wiki/Chayanda_field][fields in Siberia]] 1,000's of km apart, so the two aren't in competition. Finally, natural gas comprised only [[https://www.brookings.edu/articles/the-global-energy-trades-new-center-of-gravity/][3.2% of Chinese power generation]] in 2019[fn:8].

As a result of European support for Ukraine, Russia has [[https://www.cnn.com/2022/06/23/energy/germany-russia-gas-alarm/index.html][cut gas shipments to the EU]], even its biggest customer, Germany. While Russia had demonstrated in the past that it's an [[https://www.brookings.edu/blog/order-from-chaos/2019/08/30/heading-for-another-ukraine-russia-gas-fight/][unreliable supplier]] over political-security issues, the low prices and avoidance of disruption to big buyers had always ensured market share for Gazprom. Now, however, [[https://www.bloomberg.com/news/articles/2022-06-07/the-us-is-now-sending-the-bulk-of-its-export-gas-to-europe][US LNG]] is rapidly entering the EU market, [[https://www.bloomberg.com/news/articles/2022-07-01/us-lng-supplies-to-europe-overtake-russian-gas-iea-says#xj4y7vzkg][overtaking Russian piped gas]] for the first time in June, while smaller consumers like [[https://www.npr.org/2022/05/26/1101568189/lithuania-has-become-the-1st-european-country-to-stop-using-russian-gas][Lithuania]] are actively weaning themselves off Gazprom altogether. Even Germany, the staunchest defender of "engagement" with Russia, has [[https://www.reuters.com/business/energy/germanys-scholz-halts-nord-stream-2-certification-2022-02-22/][suspended]][fn:9] the controversial Nordstream 2 pipeline.

The other large fossil fuel, oil, is a similar story. While China is Russia's largest oil export market, the total trade amounted to just [[https://oec.world/en/profile/bilateral-product/crude-petroleum/reporter/chn#:~:text=China%20imports%20Crude%20Petroleum%20primarily,and%20Norway%20(%242.5B).][$23.8 billion in 2020]]. As China's total import was about $150 billion, Russia accounted for <16% of the market. In 2021 Russia was only the world's [[https://www.weforum.org/agenda/2022/04/which-petroleum-products-does-russia-supply-to-world/][third largest oil producer]], behind the United States and Saudi Arabia--and that was before oilfield services companies like Halliburton [[https://www.theguardian.com/business/2022/mar/19/halliburton-schlumberger-suspend-operations-russia][pulled out]], which will negatively impact Russian production in the medium to long term. While Russia has tried to keep exports going with [[https://www.bloomberg.com/news/articles/2022-05-31/the-deepening-discounts-on-russian-oil-in-the-country-s-own-data][deep discounts]], it's [[https://www.bloomberg.com/news/articles/2022-07-04/russia-s-crude-oil-shipments-to-crucial-asian-markets-falter#xj4y7vzkg][India, not China]], that's snapped up most Russian seaborne crude.

Looking at the bigger picture, while China is Russia's [[https://wits.worldbank.org/countrysnapshot/en/RUSSIA][largest trading partner]], Russia isn't even among China's [[https://www.worldstopexports.com/chinas-top-import-partners/][top ten]]. The US is far and away number one, with Japan, Korea, Germany, the Netherlands, and the UK among others. Small wonder, then, that despite the supposed "unlimited partnership" Chinese firms like Union Bank have [[https://fortune.com/2022/04/22/unionpay-china-credit-card-sberbank-secondary-sanctions-russia/][stopped services]] in Russia for fear of running afoul of Western sanctions. Even Huawei, that favorite US sanction target, has [[https://www.tellerreport.com/news/2022-06-08-ria-novosti--huawei-has-closed-part-of-the-official-retail-outlets-in-russia.Sy76ZOICdq.html][shut stores]] in Russia due to parts shortages. With household consumption comprising [[https://www.ceicdata.com/en/indicator/china/private-consumption--of-nominal-gdp][<40% of GDP]], the lowest among major economies, China /must/ have access to export markets. A Russian economy in [[https://tass.com/economy/1459911][severe contraction]][fn:10] is of less value, not more. Even if bridges need to be burned with the West one day, it's not going to be here and now, on Putin's behalf.

** East is east, west is west

One reason that Germany and Japan forged a partnership during WWII was that they were on opposite sides of the globe. While Germany was busy sweeping across Europe, Japan was wholly focused on Asia. The one country both did fight with was the Soviet Union, though [[https://en.wikipedia.org/wiki/Soviet%E2%80%93Japanese_Neutrality_Pact][not at the same time]][fn:11]. As the military situation went south, neither could (or would, for that matter) come to each others' aid, allowing the Allies to defeat them in isolation.

China and Russia have a similar dynamic. Though the two share a border, their core areas are far apart--Russia's in Europe, China's on the North China Plain. For all the speculation about global warming turning [[https://www.nytimes.com/interactive/2020/12/16/magazine/russia-climate-migration-crisis.html][Siberia into a new breadbasket]], the reality is that Russia's population east of the Urals is [[https://www.washingtonpost.com/world/2020/12/01/russia-population-decline-putin/][in decline]], as is [[https://www.scmp.com/economy/china-economy/article/3168090/china-population-rust-belt-province-heilongjiang-unveils-plan][China's in the northeast]]. In fact, northern China as a whole is seeing its [[https://www.aljazeera.com/economy/2021/4/28/bb-mindthegap-chinas-north-south-economic-divide-seen-worsening][share of population and economy shrink]], accounting for only 35.2% of GDP in 2020 compared to 42.9% in 2012, making the economic rationale of e.g. a new [[https://interfax.com/newsroom/top-stories/80106/][bridge across the Amur]] very dubious[fn:12].

Aside from posturing with its Soviet-era [[https://abcnews.go.com/International/wireStory/japan-sights-china-russia-warships-disputed-islands-86177724][warships near Japan]], Russia has little military capacity in the Far East[fn:13]. Since the border deal with China in the 90's, Russia pulled most troops out of the region, and its Far Eastern forces are among the least well-equipped. The invasion of Ukraine has necessitated [[https://www.rferl.org/a/russia-primorye-parliament-war-dissent/31871358.html][redeploying even more of these forces]], which have taken disproportionately high casualties. Having committed its [[https://www.bbc.com/news/world-europe-61619638][entire army and then some]] to Ukraine for the foreseeable future, Russia isn't just militarily imbalanced in Asia, but everywhere else too. In any potential conflict over Taiwan or the South China Sea, it will have no role to play, not only because it has no interest in being embroiled in a Chinese war, but also because it simply doesn't have the men or hardware.

As for China helping Russia in Europe, the idea is even more laughable. It's over 6,000 km from Beijing to Smolensk by land, much further by sea. Eastern and Central Europe have been primary [[https://carnegieendowment.org/2018/10/19/europe-s-emerging-approach-to-china-s-belt-and-road-initiative-pub-77536][targets of China's Belt and Road project]], with Ukraine in particular having been a major [[https://asia.nikkei.com/Business/Business-deals/Ukraine-blocks-Chinese-takeover-of-jet-engine-maker-on-US-urging][source of military technology]]. War has pushed not only Kyiv closer to the West, but caused countries like Lithuania to [[https://www.france24.com/en/live-news/20220309-lithuania-mania-sweeps-taiwan-as-china-spat-sizzles][reposition themselves vis-a-vis Beijing]] in order to attract more American support. China still has partners, like [[https://bbj.hu/business/tech/telco/free-to-do-business-in-hungary-huawei-looks-for-more-speed-less-energy][Hungary]] and to some extent [[https://www.reuters.com/lifestyle/sports/polands-president-attend-beijing-olympics-amidst-us-boycott-2022-01-18/][Poland]][fn:14], but in the wake of Russia unleashing the biggest war on the continent since 1945, their room to maneuver on China's behalf has [[https://www.dw.com/en/eu-triggers-rule-of-law-procedure-against-hungary/a-61607618][gotten much smaller]].

** Peter Principle for Geopolitics

So why is there such obsession over a Sino-Russian partnership which at best is two countries not getting in each others' way?

Despite the limits of the Sino-Russian relationship, it is necessary to plan for the worst. /If/ China and Russia had a complex, deeply intertwined military and economic partnership of the sort that the US has with the UK or Japan, it'd be a significant challenge. That such a scenario is nigh-impossible doesn't preclude responsible planners from gaming it out. Where these folks go wrong, however, is in drawing ludicrous conclusions--that the US should "share power" with China, or work with Russia against China, or work with China against Russia, or any number of other policy recommendations that wouldn't be fit to print on the back of a cereal box, let alone a major newspaper or policy journal.

That's the objective reason. The more important, subjective reason is that this threat reflects an American way of thinking. Unlike Europe, which doesn't see China as a threat, or Japan/Korea/Taiwan, which don't see Russia as (much of) a threat, the US sits astride both the Pacific and Atlantic[fn:15], and must deal with both. For the Americans, the world is one big [[https://www.amazon.com/World-Flat-History-Twenty-first-Century/dp/0374292884][global village]], which is why it insisted on making [[https://www.nytimes.com/2022/07/01/world/asia/china-nato.html][NATO issue a statement on China]]. In the American mind, all threats are one and the same, with Russia/China/Iran/North Korea being one large amorphous anti-American blob, like Communism was during the Cold War.

There is a danger in this type of thinking, which I'll call the *[[https://www.investopedia.com/terms/p/peter-principle.asp#:~:text=The%20Peter%20Principle%20is%20an,a%20level%20of%20respective%20incompetence.][Peter Principle]] for Geopolitics: that every alliance system is expanded ("promoted") until it ceases to be effective*. NATO expansion into Central and Eastern Europe post-Cold War has already made it an unwieldy organization always under threat of a single member's veto; adding a China element will only make it less coherent, at a time when it's barely gotten some [[https://www.economist.com/europe/2019/11/07/emmanuel-macron-warns-europe-nato-is-becoming-brain-dead][cerebral signals back]] as a result of the Russian invasion. With the addition of two more members, [[https://www.nato.int/cps/en/natohq/news_197737.htm][Sweden and Finland]], NATO's borders with Russia will suddenly double, with the [[https://www.npr.org/2022/06/29/1108536666/biden-is-boosting-u-s-troops-in-europe-because-of-russias-war-in-ukraine][US sending yet more troops to Europe]] in spite of having promised a "[[https://www.brookings.edu/articles/the-american-pivot-to-asia/][pivot to Asia]]" over a decade ago.

By not separating, independently analyzing, and crafting specific policies for different threats, and instead reaching for the most familiar hammer (NATO) to tackle every problem, the US runs the risk of investing resources in precisely the wrong areas. Russia's military is being put through a [[https://www.oryxspioenkop.com/2022/02/attack-on-europe-documenting-equipment.html][meatgrinder]] in Ukraine, with Moscow [[https://www.reuters.com/world/europe/russia-is-conducting-covert-mobilisation-campaign-ukraine-spy-chief-2022-06-25/][desperately scrounging for troops]] and pulling the [[https://www.thedrive.com/the-war-zone/ancient-russian-t-62-tanks-spotted-wearing-cage-armor-in-ukraine][oldest of extant Soviet tanks]] out of storage. Thanks to the false belief that it was a modern military power[fn:16], Russia is having to take every town in a country twice the size of Germany with artillery duels. Whatever happens in Ukraine--and the most likely scenario is a continued bloodbath for Russia--Moscow's military threat to the US--or anyone else--is greatly reduced for at least the next decade thanks to Putin's massive blunder.

** A double delusion

The "Sino-Russian delusion" is thus twofold. The first delusion is of a deep military partnership between Russia and China. The second is that an allocation of resources that treats th two threats as equal, or even gives [[https://www.france24.com/en/europe/20220629-russia-is-now-main-threat-nato-can-adjust-its-plans-and-policies-accordingly][primacy to Russia]], will serve American interests.

Rather than sending more troops to Europe, we should be pulling them out to confront the senior threat, China. While an amphibious invasion of Taiwan would be far more challenging than slow-rolling tanks into Ukraine, the former is also a lot smaller, harder to resupply, and doesn't have the benefit of [[https://en.wikipedia.org/wiki/Battle_of_Debaltseve][8 years of wartime experience]] under its belt. Furthermore, the First Island Chain doesn't have the buffer Europe does. If Russia takes Ukraine, it's face-to-face with the EU. If China takes Taiwan, it'd have free reign over the entire East and South China Seas, freed of an unsinkable aircraft carrier right on its doorstep.

Neurosis is generally an annoying but harmless characteristic. By worrying about everything, however, we effectively worry about nothing, and end up doing nothing useful. It's time to drop delusions and tackle real threats--China, not Russia, let alone Sino-Russia.

* Footnotes

[fn:1] Americans--particularly of the liberal persuasion--could use a dose of China's famous [[https://en.wikipedia.org/wiki/The_True_Story_of_Ah_Q][Ah-Q mentality]], which to this day allows 1.4 billion people to live in the fervent satisfaction of spiritual victory rather than constantly whinge about this or that.

[fn:2] I once saw a photograph collection of American and Soviet young people taken by an American visitor to the USSR, with the general theme being that while American youth were out drinking and smoking pot, their Soviet counterparts were dancing ballet and playing chess. It might have been true (at least for the youths in question), but in the end it also [[https://www.history.com/topics/cold-war/fall-of-soviet-union][didn't matter]].

[fn:3] British media, if anything, is even worse. When it comes to trash news, our mother country is still "better"!

[fn:4] When Lord Palmerston [[https://www.oxfordreference.com/view/10.1093/acref/9780191826719.001.0001/q-oro-ed4-00008130][said]] "We have no eternal allies, and we have no perpetual enemies", he no doubt was thinking about other major European powers. England's [[https://www.historyextra.com/period/medieval/qa-why-is-portugal-known-as-britains-oldest-ally/][alliance with Portugal]], a smaller power, was by then already centuries old.

[fn:5] With the United States, China loves to recount events like the 1999 [[https://www.washingtonpost.com/wp-srv/inatl/longterm/balkans/stories/belgrade050899.htm][bombing of the Chinese embassy]] in Belgrade or 2001 [[https://abcnews.go.com/International/story?id=80826&page=1][Hainan Island spy plane incident]].

[fn:6] Especially as lower tensions with Russia eliminated a large military expenditure, providing the government more resources for economic reform and weakening some of the conservative voices in the armed forces.

[fn:7] Or between Russia and any other country, or between China and any other country...

[fn:8] Compare this to natural gas in the United States, which is responsible for [[https://www.eia.gov/energyexplained/natural-gas/use-of-natural-gas.php#:~:text=The%20United%20States%20used%20about,of%20U.S.%20total%20energy%20consumption.][1/3 of energy production]].

[fn:9] Notably, suspension is not cancellation. There's still a strong element of German business and politics that believes in waiting for the conflict to blow over so they can get back to business, but by now it should be clear that this will be a [[https://www.bloomberg.com/opinion/articles/2022-06-09/a-long-war-in-ukraine-could-bring-global-chaos][long war]].

[fn:10] You know things are really bad when state media is touting that "experts" are predicting GDP will decline "only" 7.5% in 2022, instead of 9.2%.

[fn:11] Aside from American Lend-Lease, not having to fight Germany and Japan simultaneously saved the USSR from collapse.

[fn:12] Of course, such projects are always more about ceremony and symbolism than anything else, especially for the leadership of these two countries.

[fn:13] And Moscow has surely not forgotten the lesson of the 1904-05 [[https://www.history.com/topics/japan/russo-japanese-war][Russo-Japanese War]]--trying to deploy forces from half a world away when war's already started is a sure path to defeat (unless you're the Americans, in which case it's a day that ends in "y").

[fn:14] Unlike Hungary, which is cynically trying to play all sides, Poland's calculus was that China could be convinced to lean on Russia. This is, however, a misunderstanding of the Sino-Russian relationship, which as previously noted is one of parallels, not partnership.

[fn:15] Actually, the US sits astride the world, but let's not make the rest of the Earth feel too bad on Independence Day.

[fn:16] Or any sort of military power at all, really. Military powers have proper [[https://defence-blog.com/crashed-russian-su-34-radio-transmission-releases-im-shot-down/][air forces]] and [[https://www.cnn.com/2022/04/15/europe/russia-guided-missile-cruiser-moskva-sinks-intl-hnk-ml/index.html][navies]], you know.
