#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: Putin's political constraints
excerpt: Understanding how the Ukraine War will progress
---
#+END_EXPORT

When Russia began its military buildup on the Ukrainian border from late 2021 to early 2022, the United States loudly and publicly [[https://www.nytimes.com/live/2022/02/11/world/russia-ukraine-news][warned Ukraine and the Europeans]] that a full-scale invasion was imminent. Not only were Western European countries like [[https://www.express.co.uk/news/politics/1656383/france-germany-russia-war-putin-ukraine-invasion-USA-warning-macron-merkel][France and Germany]] dismissive of the idea[fn:1], but [[https://www.theguardian.com/world/2022/jun/11/volodymyr-zelenskiy-didnt-want-to-hear-warnings-of-russia-invasion-says-joe-biden][so was Kyiv]]. The result was a swift Russian takeover of [[https://en.wikipedia.org/wiki/Battle_of_Kherson][large swatches of southern Ukraine]] in only a few days even as another group of units put the [[https://www.reuters.com/world/europe/ukraines-president-stays-put-russian-invaders-advance-2022-02-25/][capital under siege]]. Russia seemed poised to sweep over the country and depose the Zelenskyy government.

Soon, however, things began going south. Its forces were not welcomed, as it'd claimed, but the target of [[https://www.bbc.com/news/world-europe-60632587][protests]] and [[https://www.youtube.com/watch?v=ibgqKnhOugU][partisan activity]]. In the north, a vast [[https://www.newsweek.com/russian-column-convoy-mechanical-breakdown-invasion-force-military-kyiv-ukraine-1684396][convoy of vehicles ground to a halt]] due to congested roads and lack of fuel. The Ukrainian political leadership did not flee, as expected, and its armed forces, comprising in large part of hastily-raised militia, [[https://www.oryxspioenkop.com/2022/04/destination-disaster-russias-failure-at.html][fought back fiercely]]. As a result, Russia was forced to [[https://www.reuters.com/world/us-assesses-russia-completes-withdrawal-around-kyiv-us-defense-official-2022-04-06/][withdraw from Kyiv]] with heavy casualties only a month later.

Since then Moscow has suffered humiliation after humiliation, from the [[https://www.nytimes.com/2022/04/14/briefing/russia-ukraine-war-flagship-mariupol.html][sinking of its Black Sea flagship]] to the [[https://apnews.com/article/russia-ukraine-explosions-fires-kharkiv-a5d6dd74e0fc8301cdd87601f5e2db1f][bombing of the Crimean bridge]]. The Kremlin is so desperate to stem setbacks[fn:2] that it's resorted to a "[[https://www.nytimes.com/live/2022/09/21/world/russia-ukraine-war-putin][partial mobilization]]"[fn:3], which it had [[https://www.plenglish.com/news/2022/05/04/russia-denies-plans-to-declare-general-mobilization-on-may-9th/][long denied]] would be needed. In short, the Russian military has exposed itself as a decrepit force, a far cry from the 1980's Soviet Union[fn:4], let alone today's NATO.

The shift in momentum has led to [[https://cepa.org/article/crimea-in-ukraines-crosshairs-say-us-generals/][premature celebration]], however. Much focus is on Russia's material losses, such as [[https://www.oryxspioenkop.com/2022/02/attack-on-europe-documenting-equipment.html][tanks blown up]] or planes shot down. This bean-counting misses the point entirely[fn:5]. Though Ukraine is on the offensive, whether the conflict continues still lies entirely in Putin's hands, and his decision has nothing to do with men being killed or vehicles blown up.

** Russia's attitude towards Ukraine

Russian messaging towards Ukraine since the start of the invasion has been schizophrenic. On the one hand, there are emotional appeals to the two countries' [[https://www.aljazeera.com/news/2022/2/25/history-of-ties-between-ukraine-and-russia][ethnic similarity and shared history]], which tends to be swiftly followed by genocidal threats to [[https://www.justsecurity.org/81789/russias-eliminationist-rhetoric-against-ukraine-a-collection/][end Ukraine]] not only as a state but a culture.

This contradiction can be easily understood by anyone who's dealt with a partner in an abusive relationship. Russia feels like it owns Ukraine, but does not want to take full political and economic responsibility for it--the strains of doing so had weighed down and ultimately destroyed the Russian Empire and Soviet Union. Instead, it wants to deny Ukraine to others, to make sure its jilted lover never loves again.

George Friedman, formerly of Stratfor, [[https://worldview.stratfor.com/article/ukraine-edge-empires][wrote]] about the importance of Ukraine to Russia over a decade ago, comparing it to Texas for the United States[fn:6]. A hostile Ukraine would make Belgorod, once the heart of the Greater Russia, a border town. It would leave Moscow 400 miles from long, indefensible borders. In [[https://www.amazon.com/Next-Decade-Empire-Republic-Changing/dp/0307476391][The Next Decade]], published nearly exactly ten years ago, Friedman predicted that a resurgent Russia would seek to [[https://www.youtube.com/watch?v=Wdni_hVdjTU][re-establish influence]] over the Former Soviet Union (FSU). Friedman's colleague Peter Zeihan, in his book 2014 book /The Absent Superpower/, predicted a [[https://www.youtube.com/watch?v=rkuhWA9GdCo][Twilight War]] in which Russia would act against not only Ukraine but the Baltics, which Russian leadership has [[https://www.npr.org/2022/06/30/1108843823/tensions-are-on-the-rise-between-russian-and-europes-baltic-region][not been shy about threatening]].

Since the implosion of the USSR, Russia has faced the challenge of maintaining influence over the FSU in order to secure its borders. During the chaotic 90's Moscow lost control of all its former clients and even [[https://en.wikipedia.org/wiki/First_Chechen_War][gave up de facto governance]] of regions within Russia like Chechnya. Putin has spent two decades rebuilding Russian power, effectively re-establishing control over Chechnya, [[https://en.wikipedia.org/wiki/Russo-Georgian_War][Georgia]], and [[https://en.wikipedia.org/wiki/2020%E2%80%932021_Belarusian_protests][Belarus]][fn:7]. Ukraine, the most important of these former clients, has been caught in a tug-of-war since the [[https://en.wikipedia.org/wiki/Orange_Revolution][Orange Revolution]], and Putin's determined to force it back into the Russian camp once and for all.

** The limits of Russian capability

Unfortunately for Putin, his ambitions are not supported by Russia's economic, demographic, and technological reality.

In the mid-60's, the USSR had a GDP roughly [[https://www.quora.com/On-its-peak-days-what-was-the-Soviet-Union-s-GDP-vs-the-USA-s][60% that of the US]]. Though this proportion declined during the 1970's stagnation, the USSR remained the world's [[https://www.theodora.com/wfb/1990/rankings/gdp_million_1.html][second largest economy]] all the way until collapse. It kept this position thanks to the world's [[https://en.wikipedia.org/wiki/Soviet_Census_(1989)#Ranking_of_Soviet_republics][third largest population]]. Soviet technological achievements from deep sea to space don't need recounting, and it maintained leadership in military fields such as [[https://www.warhistoryonline.com/war-articles/mig-31.html?chrome=1][aviation]].

Today's Russia is a shadow of the USSR. Its GDP is 1/15 that of the US, its population less than half[fn:8], its weapons can't be built without [[https://thehill.com/policy/international/3593133-hundreds-of-western-components-found-in-russian-weapons-in-ukraine-think-tank/][Western components]], and it's being cut off from the basics of modern life such as [[https://blogs.microsoft.com/on-the-issues/2022/03/04/microsoft-suspends-russia-sales-ukraine-conflict/][computer operating systems]] and [[https://www.reuters.com/business/us-official-says-export-curbs-russia-hit-car-production-tank-building-2022-03-30/][automobiles]]. Putin stabilized Russia after the chaotic Yeltsin years by focusing on natural resources, but the result is a regression from an industrial economy to a primary one. Add to this the country's [[https://novayagazeta.eu/articles/2022/10/02/where-did-they-disappear-to-russian-local-pm-says-1-5-mln-military-uniforms-are-missing-news][typical corruption]] and the result is a hollow force that emptily boasts about [[https://news.usni.org/2022/07/08/doomsday-submarine-armed-with-nuclear-torpedoes-delivers-to-russian-navy][nuclear torpedoes]] while having [[https://www.lbc.co.uk/news/russian-conscripts-tampons-bullet-wounds-ukraine/][no medkits]] for draftees.

Ukraine, meanwhile, is no Chechnya or Georgia. It's twice the size of Germany with a population 1/3 that of Russia. Though it missed golden opportunities to prepare for invasion due to political obstinacy, the government was quick to establish conscription after war started, such that a dire manpower shortage in the beginning turned into a [[https://www.atlanticcouncil.org/blogs/ukrainealert/ukraine-can-win/][numerical advantage]] only months later. The addition of Western /wunderwaffe/ like [[https://www.businessinsider.com/russia-making-excuses-for-not-stopping-us-himars-in-ukraine-2022-10][HIMARS]] served as a force multiplier that allowed Ukraine to go on the offensive against an undermanned Russian military with forces cobbled together from contract soldiers, conscripts, mercenaries, and regional militias.

Eight months in, the conflict is going poorly for Russia. It's had to [[https://breakingdefense.com/2022/07/russia-pulls-some-wagner-forces-from-africa-for-ukraine-townsend/][withdraw mercenaries from Africa]], move [[https://www.reuters.com/world/russia-ships-s-300-air-defence-missiles-out-syria-satellite-images-2022-08-29/][air defenses out of Syria]] to defend its own territory, and turn to the likes of [[https://www.wsj.com/articles/russias-use-of-iranian-kamikaze-drones-creates-new-dangers-for-ukrainian-troops-11663415140][Iran]] and [[https://www.nytimes.com/2022/09/05/us/politics/russia-north-korea-artillery.html][North Korea]] for military support. Though giving diplomatic cover, China has not stopped its businesses from [[https://www.kyivpost.com/russias-war/chinese-unionpay-system-cuts-off-russian-bank-cards-2.html][withdrawing from Russia]], while Central Asian leaders are openly [[https://foreignpolicy.com/2022/10/06/russia-ukraine-war-central-asia-dipomacy/][asserting themselves]] against Moscow.

** Putin's popularity problem

Wars are usually popular in the beginning, and the invasion of Ukraine is no different. Putin's popularity [[https://www.statista.com/chart/28383/putin-approval/][shot up]] immediately after sending troops across the border with promise of quick victory. As the conflict ground on, however, and Russian losses mounted, cracks emerged in the Kremlin's narrative. [[https://www.washingtonpost.com/world/2022/10/06/russia-shoigu-military-failures-criticism/][Criticism of military leadership]] has become increasingly vocal from outside of state media (though Putin himself remains off-limits), while [[https://www.npr.org/2022/09/24/1124939236/russia-protest-putin-mobilization-draft-ukraine-war][protests against conscription]] have erupted all over the country[fn:9].

It is a typical refrain in democracies that dictators don't need to worry about approval ratings, but in fact they do, and more so than any elected politician. Modern dictators come to power on the backs of the masses, and remain there by keeping core constituencies happy. When too much popularity is lost, internal enemies circle, with the end result being [[https://en.wikipedia.org/wiki/Trial_and_execution_of_Nicolae_and_Elena_Ceau%C8%99escu][Ceaușescu]] or [[https://www.bbc.com/news/world-africa-47852496][Omar al-Bashir]].

Putin's been in power for two decades not only because of his security background and masterful manipulation of oligarchs, but because he paid pensions that lapsed under Yeltsin and distributed money, however little, to poor regions left to fend for themselves in the post-Soviet economic chaos. The old appreciate the stability he's wrought, while the young have known no other leader and can't imagine someone else in his position. While there is indubitably [[https://apnews.com/article/europe-russia-elections-voting-vladimir-putin-1a072af8580b05b134bd22df95a5ae83][electoral fraud]] in Russia, its purpose is to firm up support for Putin's party, not himself--he needs no help to win against a field of controlled opposition.

As such, once his maximalist goals were dashed, Putin's first concern was saving face, not battlefield outcomes. [[https://www.forces.net/russia/putin-has-taken-personal-control-russias-faltering-donbas-offensive-western-sources-claim][Direct orders]] were issued not to give up territory despite threat of Ukrainian encirclement, leading to dramatic routs and equipment losses. Mobilization was first denied, then delayed, and finally implemented only "partially", with emphasis on [[https://foreignpolicy.com/2022/09/23/russia-partial-military-mobilization-ethnic-minorities/][rural minority regions]] to avoid unrest in major cities[fn:10]. Trying to distract from defeats, Russia [[https://www.npr.org/2022/09/27/1125322026/russia-ukraine-referendums][flamboyantly annexed]] the Ukrainian regions it occupies, threatening to defend "its" new territory with nukes, then did nothing as Ukraine stormed into cities like [[https://www.theguardian.com/world/live/2022/oct/02/russia-ukraine-war-live-updates-ukrainian-capture-of-lyman-makes-war-more-difficult-for-putin-says-us][Lyman]].

At every stage of this conflict, Putin has shown that he's more concerned about appearances than facts. From [[https://www.polygraph.info/a/fact-check-russia-ukraine-kyiv-attack/6743348.html][denying]] that Russia ever wanted to take Kyiv in the first place to [[https://www.reuters.com/business/media-telecom/russian-state-media-grapples-with-kharkiv-defeats-2022-09-12/][burying the lede]] on its Kharkiv collapse, the Kremlin has constantly changed its story around goals and red lines. This confusion helps to repel criticism of Putin, even as it leads to increasingly disastrous battlefield outcomes, which is why it will continue for the foreseeable future.

** Western and Ukrainian weaknesses

All that being said, Russia can still drag the war out for a long time. Aside from ample reserves of equipment and manpower[fn:11], the Kremlin is betting that skyrocketing energy prices in Europe would weaken Western support for Ukraine, which is why it's proactively [[https://www.cnbc.com/2022/09/06/energy-crisis-why-has-russia-cut-off-gas-supplies-to-europe.html][cut off gas supplies]] to the continent and even [[https://www.bbc.com/news/world-europe-63297085][blown up]] the long-controversial Nordstream II pipeline. [[https://www.reuters.com/world/europe/thousands-czechs-protest-governments-handling-energy-crisis-2022-09-28/][Protests]] have already emerged in pro-Ukraine countries like Czechia, and it's only autumn. While natural gas prices in the EU have [[https://www.bloomberg.com/news/articles/2022-10-17/europe-gas-drops-to-3-month-low-as-eu-plans-more-crisis-measures][fallen in recent months]] due to an uptick in storage, developments like [[https://www.bloomberg.com/news/articles/2022-10-17/china-halts-lng-sales-to-foreign-buyers-to-ensure-own-supply][China's ban on LNG exports]] to ensure domestic supply do not bode well for the next few months. With an economy highly dependent on energy-intensive sectors such as chemicals and automobile manufacturing, Germany's launched a massive [[https://www.euronews.com/my-europe/2022/10/04/germany-faces-scrutiny-from-eu-peers-over-massive-200-billion-aid-scheme-to-cushion-high-g][200 billion euro]][fn:12] support program, which likely won't be the last. Smaller EU countries are in no position to replicate this, leading to [[https://www.euractiv.com/section/energy/news/eus-michel-calls-for-genuine-energy-union-in-response-to-crisis/][intra-EU tensions]].

Ukraine, meanwhile, is suffering tremendously from the war, as it's being fought almost entirely on its territory. GDP is down [[https://www.reuters.com/world/europe/ukraines-economy-shrank-by-30-first-three-quarters-2022-2022-10-08/][30% year on year]], while by July [[https://www.bbc.com/news/world-60555472][5 million]] people had left the country and millions more were internally displaced. Its budgetary needs are in the billions of dollars per month, which the EU has been [[https://www.washingtonpost.com/us-policy/2022/10/15/ukraine-us-europe-funding/][slow to give]]. While [[https://www.reuters.com/markets/asia/ukraines-marchenko-elected-chair-boards-world-bank-imf-2023-2022-10-14/][promotion of Ukrainians]] in organizations like the IMF ought to give the country more influence in directing funding to itself, it'll be far from enough to bridge the yawning gap between economic losses and increases in military and welfare needs.

In the grinding war of attrition the conflict has devolved into, Russia faces disadvantages in manpower and advanced munitions, but retains the edge in armor and airpower. Of particular concern to Ukraine ought to be its [[https://www.youtube.com/watch?v=xCEzEVwOwS4][losses in air defenses]], which is not easily replaced with either Soviet or Western systems due to limited number of available units. If Ukraine runs out of anti-air missiles, the hitherto [[https://www.newsweek.com/russian-air-force-underperforming-risk-averse-strategy-ukraine-war-british-intellegence-1717338][underperforming Russian Air Force]] may become more effective, turning the tide once again in Russia's favor.

** The war will go on

The biggest determinant of the war's continuation, however, is the fact that Putin has invested too much political capital to give up. Western media has declared that Russia's about to run out of men, missile, or will to fight[fn:13] for months, yet the Kremlin has [[https://www.npr.org/2022/10/03/1126626921/russia-is-losing-the-edge-in-ukraine-but-putin-still-seems-ready-to-double-down][doubled down]] each time. Putin knows that a catastrophic outcome in this conflict will undo everything he's accomplished over the past twenty years, if not eject him from power altogether. He's chosen to ride this tiger, and there's no getting off.

While Russia' [[https://www.npr.org/2022/10/17/1129443703/russias-nuclear-arsenal-is-huge-but-will-putin-use-it][nuclear threats]] have proven hollow so far, that's because Putin is not yet at the point of desperation. The conflict can be dialed down from "boil" to "simmer" and kept that way for years before an inflection point is reached. This is exactly what happened after the Crimean annexation in 2014. Yet, short of the West drastically curtailing its support for Ukraine, there's no off-ramp for Putin, and if nothing changes we /may/ reach such a decision moment in the future.

In that light, it's important we engage in sober analysis rather than traffic in delusions. This war is far from over; it will continue at varying intensity for the next few years, put great pressure on European economies, [[https://www.usatoday.com/story/news/world/2022/10/18/ukraine-russia-war-live-updates/10530302002/][challenge Western political will]] to keep financing Kyiv, degrade Russia but devastate Ukraine, and pave the way for the emergence of [[https://www.washingtonpost.com/world/2022/07/22/ukraine-grain-deal-turkey-russia/][new power brokers]].

Ominously, other parts of the world are also seeing an [[https://apnews.com/article/south-korea-north-joint-chiefs-of-staff-government-and-politics-e9dd7ea833f7809de151669242d88913][escalation in tension]], indicating that the global system faces systemic friction rather than a one-off. While Europe grapples with its largest conflict since WWII, the clouds of war are [[https://news.usni.org/2022/10/18/accelerated-chinese-timeline-to-seize-taiwan-raises-questions-on-pentagon-priorities][gathering elsewhere]] too. Perhaps, in retrospect, Russia's invasion of Ukraine will end up being a necessary vaccine for the West against great wars to come[fn:14]. 2022 may prove to be the most violent year in the past decade, but the most peaceful of the next.

* Footnotes

[fn:1] France [[https://www.bbc.com/news/world-europe-60938538][fired]] its military intelligence chief in March to save face. Germany, being more shameless, has done no such thing.

[fn:2] In eight months of conflict Russia's estimated to have [[https://www.newsweek.com/russian-death-toll-ukraine-war-overtakes-american-losses-vietnam-1752220][lost more men]] than the US did in ten years of Vietnam.

[fn:3] Conscription is always unpopular, but the one Putin undertook is so chaotic and unpopular that Moscow city has hastily announced [[https://www.themoscowtimes.com/2022/10/17/moscow-mayor-announces-end-of-mobilization-in-the-capital-a79107][its end]] within the capital after barely a month.

[fn:4] In the Soviet-Afghan War's opening salvo, a spetsnaz team [[https://en.wikipedia.org/wiki/Operation_Storm-333][took out the entire Afghan government]] in a few hours. 2022's Russian assault on Kyiv is a clown show in comparison.

[fn:5] In any case, [[https://www.youtube.com/watch?v=ZNNoaRp5lz0][satellite image analysis]] shows that Russia's not about to run out of tanks any time soon. And since it's never cared about human lives, it's not about to exhaust its supply of [[https://news.yahoo.com/ill-equipped-russian-soldiers-only-031757629.html][cannon fodder]] either.

[fn:6] Not /Mexico/, mind you--/Texas/.

[fn:7] The failed 2020-21 Belarussian protests spooked Lukashenko into giving up his balancing act between Russia and the West in the hopes that Russian support would save his throne. It worked, and Moscow was able to subsequently deploy large forces in Belarus in preparation for the invasion of Ukraine.

[fn:8] Modern Russia, even before dramatic declines due to [[https://www.rferl.org/a/russia-covid-population-loss/31677211.html][coronavirus]] and men [[https://www.businessinsider.com/number-of-russians-fleeing-draft-bigger-1st-invasion-force-uk-2022-9][fleeing the draft]], had a population smaller than than of the Russian SSR in the late 80's.

[fn:9] Which, notably, didn't happen in opposition to the war itself.

[fn:10] Since Putin's more popular in rural areas than in metropolises such as St. Petersburg, he can also afford to push conscription further there.

[fn:11] The availability of resources is one thing, but the ability to use them effectively is another. Russia's suffered disproportionate casualties in every war it's fought, but it's won its share of them.

[fn:12] Equivalent to 5% of GDP, much larger than the US's [[https://www.investopedia.com/terms/t/troubled-asset-relief-program-tarp.asp][TARP]] bailout for the 2008 financial crisis.

[fn:13] Rumors of [[https://ridl.io/rumours-of-a-coup-in-russia-what-does-this-really-say-about-the-putin-regime/][Kremlin coups]] have been floated since even before the war. Those who push such a narrative either have zero understanding of Russian political dynamics, or (more likely) are simply pandering nonsense to a gullible Western audience for profit.

[fn:14] Just as the [[https://en.wikipedia.org/wiki/War_in_Donbas_(2014%E2%80%932022)][Donbas War]] turned Ukraine from a military basketcase into a well-organized force, much to Russia's surprise.
