#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: The many definitions of retirement
excerpt: Discussing the "retirement age" requires context
---
#+END_EXPORT

As the global population ages, the [[https://ourworldindata.org/data-insights/japan-has-the-highest-ratio-of-elderly-people-relative-to-working-age-people-globally][dependency ratio]], i.e. number of elderly relative to the working-age population, rises inexorably. This has led many governments to forecast severe shortfalls in their pension systems and set off a wave of [[https://www.reuters.com/world/europe/germany-approves-pension-reform-incentivize-later-retirement-2024-09-04/][retirement age increases]]. This in turn has resulted in many comparisons of retirement ages between countries. Such comparisons, however, are apples-and-oranges, as "retirement age" can mean many different things across jurisdictions and time periods.

** Beating-the-odds age

When Social Security was [[https://www.ssa.gov/history/briefhistory3.html][introduced in 1935]], the age at which people could receive benefits was 65. Life expectancy for men and women alike, however, was [[https://u.demog.berkeley.edu/~andrew/1918/figure2.html][lower than that]]. Women on average lived less than 64 years, while men lived less than 60[fn:1]. While the age has [[https://www.ssa.gov/benefits/retirement/planner/1960.html][increased today to 67]], life expectancy has risen much faster, to [[https://www.politico.com/news/2024/03/21/cdc-us-life-expectancy-rises-after-two-year-dip-00148193][77.5 in 2022]]. This means that the average person can expect to spend more than a decade drawing Social Security benefits, which its architects surely did not intend.

Also consider that young people today often spend some time in higher education, thus delaying career start to the early or mid-twenties. Since it's clearly impossible for the average person to support 100% of their life with only 60% of it at work, the only solutions[fn:2] are to [[https://apnews.com/article/migration-germany-kenya-labor-market-scholz-ruto-3b15496dc33d1897914fd894ee33bc9f][get more workers]] and reduce the time they can draw benefits.

** Full benefit age

Do people actually retire at the "retirement age"? Not necessarily. Legally, it is merely the age at which full government pensions may be collected, which we may call the "full benefit age". Whether one can "retire" on that money is another matter.

One way to judge how well government pensions allow individuals to truly stop working is by comparing the [[https://www.koreatimes.co.kr/www/tech/2024/09/129_352001.html][legal vs. effective retirement ages]]--i.e. when people start drawing benefits vs. when they exit the labor force. Western countries typically have a small difference between the two, with many retiring /earlier/ than expected due to being able to receive partial benefits. Asian nations, however, tend to have large gaps. China's retirement age for men is [[https://www.morganlewis.com/pubs/2024/09/china-announces-plan-to-gradually-increase-statutory-retirement-age#:~:text=In%20general%2C%20the%20current%20statutory,managers%20is%2055%20years%20old.][60]], yet the effective retirement age is 66. Indonesia claims people can retire at [[https://www.makarim.com/news/new-implementing-regulations-on-indonesia-s-pension-and-old-age-security-programs][58]], yet most don't do so until 69. It's a similar story with South Korea and Japan, although the gaps are smaller than in developing countries.

Another way is to assess the [[https://www.oecd-ilibrary.org/docserver/c3f27e35-en.pdf][elderly poverty rate]]. South Korea's, at [[https://www.koreaherald.com/view.php?ud=20240311050551][over 38%]], is the highest in the OECD[fn:3]. The proliferation of [[https://koreajoongangdaily.joins.com/2014/10/17/economy/Forced-from-jobs-retirees-enter-a-game-of-chicken/2996184.html][chicken restaurants]] in the country is credited to the waves of older employees forced out of their jobs and turning to menial service work to make a living. In Japan, where [[https://www.economist.com/asia/2024/05/02/japan-and-south-korea-are-struggling-with-old-age-poverty][over 20%]] of the elderly live in poverty, [[https://www.smejapan.com/business-news/how-gig-economy-is-changing-the-traditional-work-setup-in-japan/][crowdsourcing platforms]] have become a popular way for senior citizens to find contract work. These phenomena underscore how public pensions in these countries are insufficient for comfortable retirements.

** Legal firing age

South Korea is known for its powerful unions, which played a major role in the country's economic development and democratization. Yet, their demands appear incomprehensible to many outside the country. In 2023, unions demanded that retirement ages be [[https://www.koreatimes.co.kr/www/tech/2024/09/129_352001.html][raised]], while in France they [[https://apnews.com/article/france-protests-retirement-age-macron-strikes-1abb098b104f2b7094e51e650218771d][protested]] against the same. Why the difference?

As with most things, Korea imitates Japan. The post-war growth of the latter was closely associated with a system of [[https://en.wikipedia.org/wiki/Sh%C5%ABshin_koy%C5%8D][lifetime employment]], under which an employee who joined a firm could remain for the duration of their career. Yet, employees can't stay on forever, and companies know older workers' productivity cannot match that of younger ones. It was socially unacceptable, however, to get rid of some workers and not others. As a result, laws were passed to allow companies to eliminate /all/ workers at a certain age via [[file+sys:][mandatory retirement]], which is [[https://asia.nikkei.com/Spotlight/Work/OECD-urges-Japan-to-scrap-mandatory-retirement-amid-labor-shortage][typically set at 60]].

What it means in practice is that firms tend to fete their newly-minted sexagenarians with pink slips. In response, a [[https://qz.com/japan-s-labor-crunch-is-so-acute-that-companies-are-hir-1850734341][2013 law]] was passed requiring employers to keep workers on until age 65 if they wished to work longer. Firms responded by rehiring their employees at [[https://mainichi.jp/english/articles/20210423/p2a/00m/0op/026000c][lower salary]]. This legal charade has normalized into companies automatically presenting workers with revised contracts asking them to do the same work at half pay.

South Korea has yet to catch up to Japan in raising the mandatory retirement age, but it does have plans to [[https://linksinternational.com/retirement-age-in-south-korea/][increase the full benefit age]]. This exposes a potential gap for those in their early-60's, when they're too old to work and too young to draw pensions[fn:4]. Thus, the union demands for a higher mandatory retirement age is a demand not to be left hanging by mismatched government policy.

** Urban privilege age

In some countries, retirement benefits are dependent on where the recipient lives. Nowhere is this more true than in China, which institutionalizes the difference between [[https://www.cecc.gov/recent-chinese-hukou-reforms][urban and rural residents]]. The [[https://www.socialprotection-toolbox.org/practice/chinas-new-rural-and-urban-pension-schemes][National Rural Pension Scheme]] (NRPS), introduced in 2009, guarantees a grand total of 55 RMB a month[fn:5] to the elderly, and only if their children are contributing to the program. The Urban Residents Pension Plan (URPP), on the other hand, is [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10187591/][far more generous]], leading to a stark difference in retirement ages between city and country folk.

While adjusting for cost-of-living might make sense, these differences are not the result of statistical considerations, only political ones. Just as [[https://www.reuters.com/world/china/shanghai-hit-by-covid-protests-anger-spreads-across-china-2022-11-27/][protests in Shanghai]] could force change in government COVID policy while [[https://www.bbc.com/news/world-asia-china-63766125][those in Xinjiang]] could not, the government's calculus is that urban unrest is more problematic than rural impoverishment. Such logic is not limited to China, but its starkness there allows for clearer observation.

** Bureaucrat cash-in age

There is a class of employees which in nearly all countries /can/ stop working at the statutory retirement age and live comfortably: government workers.

What sets these people apart is their political influence. In democracies their election endorsements can make or break campaigns, but in all regimes they are responsible for daily governance, and no ruler can succeed without getting them on-side. Their salaries are usually not high, but their [[https://www.pinesfederal.com/legal-blog/legal-rights-for-fired-federal-employees/][rice bowls are made of iron]]. Their comfort in retirement is guaranteed less by money and more by a wide array of benefits, such as [[https://www.va.gov/health-care/][special healthcare programs]].

Many of these workers, particularly those in law enforcement and the military, retire with full benefits after twenty years. They can then return to work and [[https://www.commerce.gov/hr/practitioners/compensation-policies/general-pay/dual-compensation][draw another salary]] without penalty. This is common enough that some federal employees have even tried to [[https://www.nbcwashington.com/news/local/ex-dc-official-with-secret-2nd-job-is-referred-for-investigation-in-northern-virginia/3689345/][take another job]] before they've retired from the first one. Given that no one apparently had any performance-related complaints about Ms. Lian's absences[fn:6], we can only assume that the average bureaucrat's job is not too demanding.

** Setting your future on FIRE age

A niche trend these days is the [[https://www.youtube.com/watch?v=SEItn9Csitg][Financial Independence, Retire Early (FIRE)]] movement, which advocates extremely low expenses in one's twenties in the hopes of securing enough savings to retire in their forties (or even thirties). Like most popular financial advice, it appeals to the lower classes, whose daily lives balance on a knife's edge between solvency and disaster, promising a light at the end of their tunnel of suffering[fn:7].

Avoiding "unnecessary" expenses and keeping a rainy day fund are common sense, and some FIRE principles, like the [[https://www.nerdwallet.com/article/investing/financial-independence-retire-early][Rule of 25,]] are derived from much older, generally solid retirement advice. What "influencers" tends to advocate, however, is an ultra-lean financial diet that is particularly unsustainable to those who are already making little money. Furthermore, there are opportunity costs--such as the social networking events passed up due to miserliness--which may render such strategies penny-wise, pound-foolish.

Retiring at an early age also introduces big risks. If the stock market suddenly crashes and we get Great Depression 2: S&P Boogaloo, a forty-year-old who's been out of the workforce for the past half-decade is not going to be an attractive candidate for the few jobs still available. Retirees also [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6153553/][mentally decline]] faster than their working peers and report [[https://jech.bmj.com/content/78/10/602][higher rates of loneliness]].

When pressed, many FIRE advocates will say that "financial independence" is the real goal, "early retirement" merely a consequent possibility. Those with the former don't /have/ to spend their days sitting on the couch watching television. The supermarket shelf stockers who buy their courses, however, are probably not thinking about using their fiscal freedom to engage in public scholarship. And in any case, spending several hundred dollars on a "[[https://www.ourrichjourney.com/firemasterclass][masterclass]]" for pedestrian advice that could be found in any personal finance book published within the last century is not the best way to achieve your financial goals, whatever they may be.

** When should you retire?

Tackling this question as a thirty-something may be the height of pontification, but the answer is obvious: when the costs of working exceed the benefits.

This is easier to assess for physically demanding jobs. A young construction worker in may pick up all the shifts he can get, but an older one must consider whether misaligning his back further is worth the extra two grand. For white collar professionals, trade-offs tend to involve time rather than thoracic vertebrae, but either way, a man who's making the same career decisions at forty as at twenty has wasted two decades of his life.

Some who claim their jobs are a calling, like doctors, want to keep working [[https://www.cnbc.com/2023/04/11/i-am-100-years-old-and-the-worlds-oldest-practicing-doctor-what-i-never-do-to-live-a-long-happy-life.html][as long as they can]], but if they keel over the operating table it's the patient who pays the price. Thus the consideration for whether someone should keep working rests not only with them, but the whole of society. Western countries find mandatory retirement [[https://www.timeshighereducation.com/news/professor-sue-cambridge-over-forced-retirement-rules][controversial]], yet there are clearly valid arguments for it as applied to certain jobs under certain conditions. Just because the East Asian implementation is poor doesn't mean the idea has no merit.

There are many whose unfortunate lot in life sees them unable to save meaningful money over their whole careers. Social Security and other programs should provide a safety net for them to stop working. But at what age? That should depend on the type of work they've done. Those who've busted their knees installing masonry deserve to retire earlier than those who've strained their wrists generating [[https://www.youtube.com/watch?v=Sy5c9tJYyQI][TPS reports]]. Paper pushers, especially for the government, shouldn't be prioritized for pension checks. Tracking this stuff will be hard, but no harder than hunting down tax evaders[fn:8].

* Footnotes

[fn:1] The numbers are skewed by [[file+sys:][high infant mortality]], so adults will have lived a bit longer. Still, many would not have lived to the age for collecting government checks.

[fn:2] According to our politicians and captains of industry, who have clearly considered all options that are in the public interest.

[fn:3] Poverty is relative, but it does say something about how a society organizes itself.

[fn:4] Pensions which, as previously mentioned, are too low to allow them to stop working anyway.

[fn:5] That's the starting rate, which goes [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8051794/][up to 593 RMB]], or $84 at time of writing. That's very little money, even in rural China.

[fn:6] At least she didn't get away with it for [[https://www.bbc.com/news/world-europe-56822571][15 years]]!

[fn:7] FIRE has a lot in common with China's [[https://www.bbc.com/news/world-asia-china-57348406][Tang Ping]] ("lying flat") movement, which advocates that young people exit the rat race by moving to cheaper locales and cutting expenses.

[fn:8] If you're not a household name, you're not going to outrun the IRS.
