#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: The price of incoherence
excerpt: The Democratic coalition is increasingly unworkable
---
#+END_EXPORT

Donald Trump's [[https://www.nbcnews.com/politics/2024-elections/president-results][decisive victory]] in the 2024 elections capped a long redemption arc that began with his defeat in 2020. After 2016 the Democrats had written him off as a morbid curiosity and the product of [[https://www.reuters.com/article/world/democrats-sue-russia-trump-campaign-for-alleged-2016-election-conspiracy-idUSKBN1HR2BE/][Russian interference]], but post January 6 decided to [[https://www.reuters.com/legal/what-are-charges-against-donald-trump-classified-documents-case-2023-06-13/][use the judiciary]] to try and eliminate him as an opposition candidate. Somehow, Trump managed to not only survive the Democrats' lawfare, but to strengthen his grip on the Republican Party and storm back to victory. How was this possible, and what does it portend for the future of American politics?

** An incoherent coalition

The modern Democratic Party is the brainchild of FDR, who brought together Northern blacks and Southern whites, factory workers and farmers, to win an unprecedented four terms. This multi-racial blue-collar coalition has served as the foundation of Democratic politics ever since, expanding over time to include women, immigrants, and other "disadvantaged" groups.

A major tweak to the formula occurred after the Cold War. Globalization was the zeitgeist, epitomized by the presidency of Bill Clinton, who signed [[https://clinton.presidentiallibraries.us/items/show/101726][trade deals]] and [[https://www.theguardian.com/world/2014/apr/19/wall-street-deregulation-clinton-advisers-obama][deregulated banking]]. As a result, the party became increasingly reliant on white-collar professionals who benefited from such policies, leading to an edge among the [[https://www.pbs.org/newshour/show/how-a-college-degree-is-one-of-the-best-predictors-of-which-candidate-voters-support][college-educated]] but a deficit with the [[https://www.reuters.com/world/us/trumps-return-power-fueled-by-hispanic-working-class-voter-support-2024-11-06/][working class]].

In recent years, this model has come under increasing strain. It's hard to put suburban professionals and inner-city laborers, union members and illegal aliens, LGBT and Arabs into the same political bucket. The only way this coalition could avoid paralytic infighting was if the groups were kept separate. For many elections Democrats staved off tensions by offering divergent, often contradictory policies to different people. They didn't try to sell environmentalism to African-Americans, for example, just as they avoided advertising gender politics to Muslims.

In today's integrated media landscape, however, this two-faced approach is untenable. Environmentalists were outraged when Biden [[https://apnews.com/article/alaska-oil-biden-willow-drilling-climate-24f135580259b9f9b245383dba921fe7][approved Alaskan oil projects]], while Gaza protestors were [[https://apnews.com/article/harris-gaza-protests-rallies-wisconsin-d6aac06c7492bd4c93c567d70aaba38e][inveterate critics]] of Harris' Israel stance. Voters want to see consistency, which is rarely possible, so smart candidates offer simplicity instead. Slogans such as "Yes we can!" or "Build that wall!"[fn:1] work much better than a nine-page "[[https://kamalaharris.com/wp-content/uploads/2024/10/FMfcgzQXJZxzLGgcKmSNQSXCRKXShwxJ.pdf][Opportunity Agenda]]". A shoutable phrase not only makes a candidate look strong, but offers flexibility for their agenda once in office. The politics of policy, if it ever was a viable strategy, is certainly not the best path to the White House today.

** Weak candidates never win

[[https://www.nytimes.com/2024/11/07/us/politics/democrats-kamala-harris.html][Recriminations]] started soon after the Democrats' electoral drubbing, with the Biden camp quick to suggest that Harris was a [[https://www.newsweek.com/joe-biden-election-winner-donald-trump-kamala-harris-1976870][weak candidate]]. Their argument has merit--she [[https://www.nytimes.com/2019/11/29/us/politics/kamala-harris-2020.html][dropped out]] of the 2020 primaries before 2020 even arrived, citing a lack of money and voter enthusiasm. [[https://www.washingtonpost.com/politics/2021/12/04/kamala-harris-staff-departures/][Former staffers]] have panned her leadership style[fn:2]. She often appeared flustered and ill-prepared, leading even Democratic strategists to accuse her of [[https://www.foxnews.com/video/6363684018112][word salad]]. On the campaign trail she came across as anemic, relying on the star power of [[https://www.newyorker.com/news/the-lede/the-obamas-campaign-for-kamala-harris][Barack Obama]] and [[https://apnews.com/article/beyonce-kamala-harris-6b3f928bb7fd5a705f32ac3d04b89ed8][Beyoncé]] to rile up the crowd.

As a candidate, Harris was widely viewed as a [[https://www.latimes.com/politics/story/2024-10-09/2024-election-kamala-harris-was-known-as-the-female-barack-obama-is-that-a-good-thing][new Obama]]. For years campaign strategists had mused about [[https://www.nbcnews.com/politics/2024-election/michelle-obama-former-first-lady-not-running-president-2024-rcna141767][Michelle Obama running for office]], but when it became clear she had no interest, they sought out Harris as an off-brand alternative. Like Obama, she's half-black and not of African American ancestry (her father's [[https://en.wikipedia.org/wiki/Donald_J._Harris][Jamaican]]). Both spent some portion of their childhood abroad (Obama in Indonesia, Harris in Quebec). Both served less than a full term as senator before entering the White House. Neither had eventful careers before seeking the highest office.

The problem is that 2024 is not 2008, and Kamala is no Barack or Michelle. The novelty of a black president long ago wore off, and at 60 Harris doesn't have the youthful appeal Obama had at 47. On the campaign trail she [[https://www.aljazeera.com/news/2024/10/30/why-has-kamala-harris-downplayed-her-gender-and-race-on-the-campaign-trail][downplayed her gender]], perhaps having seen that being a woman didn't do Hillary Clinton any favors. She framed her agenda as "[[https://19thnews.org/2024/09/kamala-harris-campaign-strategy-joy/][joy]]", of all things, at a time when the population [[https://www.nbcnews.com/politics/2024-election/two-thirds-voters-say-country-wrong-track-ahead-2024-election-rcna172873][wasn't feeling particularly ecstatic]]. Her greatest strength, at least compared to Biden, was [[https://www.nytimes.com/2024/10/30/us/politics/biden-comments-harris-campaign.html][avoiding gaffes]], but that's thin gruel with which to feed a presidential run.

** The incumbency stigma

The Harris campaign was quick to [[https://apnews.com/article/biden-harris-blame-election-loss-5588bafd05471d4c4fb0145db21291d2][fire back]] that, as Biden's vice president, she bore the burden of his incumbency. Ruling parties around the world have suffered setbacks in recent years. In the Netherlands, a "far-right" candidate [[https://www.bbc.com/news/articles/cd1r0xvn0z5o][came first]]. In India, Modi's BJP [[https://www.nbcnews.com/news/world/india-election-modi-bjp-lost-majority-election-surprise-rcna155557][lost its majority]]. Even in Japan, which has been virtually a single-party state since the end of WWII, the ruling LDP [[https://www.cnn.com/2024/10/27/asia/japan-ruling-party-loses-majority-election-intl/index.html][lost power]] for only the third time in its history.

The truth is that the VP has little authority in American politics, but Harris could hardly defend herself by pointing out she didn't do anything for four years. She was blamed for [[https://www.theguardian.com/commentisfree/2024/oct/09/trump-harris-inflation-economy][high inflation]] and the [[https://www.bbc.com/news/articles/c3gdjjlydp4o][surge in illegal aliens]], with the latter accusation particularly hard to shake given her [[https://www.nbcnews.com/politics/white-house/biden-taps-harris-lead-coordination-efforts-southern-border-n1261952][assignment by Biden]] to be the "border czar". But the first rule of politics is that you're responsible for everything happening under your watch, and Harris paid the price.

The situation was certainly not helped by Biden's insistence that he would [[https://www.nbcnews.com/politics/2024-election/biden-stems-democratic-defections-insists-wont-quit-2024-race-rcna160864][continue to run for re-election]] even after a [[https://www.nbcnews.com/politics/2024-election/biden-debate-performance-democrats-panic-rcna157279][disastrous debate performance]]. It took the public defection of nearly all senior Democrats, as well as the [[https://www.nbcnews.com/politics/2024-election/nancy-pelosi-helped-pressure-joe-biden-end-2024-campaign-rcna162943][intervention of Nancy Pelosi]], to force him out. Biden took his revenge by [[https://www.nytimes.com/2024/11/08/us/politics/pelosi-harris-biden-open-primary.html][denying the Democrats a primary]], endorsing Harris immediately after exiting the race. With barely three months to act, [[https://www.nytimes.com/2024/10/21/us/elections/harris-trump-campaign-finance.html][no amount of money]] could have salvaged her campaign.

** Destiny denied

Democrats have long banked their political future on the idea that "[[https://www.bbc.com/news/articles/c0mzl7zygpmo][demography is destiny]]", expecting that a rising share of non-whites would deliver them election victories on a silver platter. The past three presidential contests, however, has thrown this idea out the window. Already in 2020 there was a [[https://www.tianxiangxiong.com/2020/11/04/apres-trump-lorban.html#fnr.7][clear indication]] of Trump gaining minority votes while (slightly) losing whites, and 2024 has only [[https://www.cnn.com/interactive/2024/politics/2020-2016-exit-polls-2024-dg/][reinforced that trend]]. White voters, college-educated or not, were less likely to vote Trump, as were seniors. Meanwhile, he gained a record 45% of Hispanics, including [[https://www.nbcwashington.com/decision-2024/2024-voter-turnout-election-demographics-trump-harris/3762138/][54% of Hispanic men]], barely below the 59% of white men he'd clinched. That Trump had appeal for socially-conservative Hispanics was [[https://zeihan.com/american-evolutions-part-3-of-3-beyond-democrats-and-republicans/][noted]] by some analysts, but [[https://www.newsweek.com/hispanic-latino-voters-democrats-progressive-1963627][taken seriously]] by few. Now, those who'd slept on this phenomenon have been [[https://www.politico.com/news/2024/11/06/democrats-latino-vote-trump-00187991][jolted awake]].

This second loss to Trump has splintered the Democrats, with some blaming the party for giving too much attention to [[https://www.nbcnews.com/nbc-out/out-politics-and-policy/democrats-blame-partys-position-transgender-rights-part-harris-loss-rcna179370][niche issues like transgenderism]], which turned off swathes of conservative minority voters. Others [[https://www.nytimes.com/2024/11/06/us/trump-immigration-border.html][openly blasted]] the Biden administration for causing the migrant crisis, though some Democrats, like NYC mayor Eric Adams, was banging that drum [[https://gothamist.com/news/mayor-adams-wont-stop-blaming-biden-for-the-migrant-influx-both-dems-could-get-stung][long before the election]]. A few have even [[https://www.youtube.com/watch?v=TLiXHQJF-Ec][turned against minorities]] altogether, blaming them for Trump's victory[fn:3].

The right lesson to be learned is that race is not the single issue that animates voters, and reducing millions of people to their skin color is not a winning strategy. The question is whether the institutionally ossified Democrat Party will learn it. Peripheral figures like Bernie Sanders have been [[https://thehill.com/homenews/campaign/4982862-bernie-sanders-working-class-angry/][scathing]] towards the party's inability to connect with the working class, yet grandees like Pelosi have [[https://www.firstpost.com/world/united-states/pelosi-blames-bidens-delayed-exit-for-democrats-defeat-says-issues-of-guns-god-gays-helped-trump-13833631.html][doubled down]] on blaming backcountry hicks for recent losses. Scapegoating rural whites may satisfy yuppies, but it's unlikely to win back the voters Democrats need.

** No outside savior

In 2012, coming off another stinging defeat to Barack Obama, the Republicans performed a [[https://abcnews.go.com/Politics/OTUS/rnc-completes-autopsy-2012-loss-calls-inclusion-policy/story?id=18755809][campaign autopsy]] and concluded that they needed to be more like the Democrats, backing "immigration reform" and trying to pick away "African-American, Latino, Asian, women and gay voters." What they had no intention of changing was the party's economic policy, centered around sacred cows like free trade and globalization. Little could they have known that when Trump [[https://www.theguardian.com/us-news/2019/jun/13/donald-trump-presidential-campaign-speech-eyewitness-memories][came down the escalator]] in 2015, he'd set off a chain of events that remade the party in a very different way.

Trump's takeover of the GOP was possible not only because of the party's weakness after two straight losses, but also its fragile internal structure. The Republican Party was a confederation of regional potentates--the Romneys in Utah, McCains in Arizona, Bushes in Texas, etc. There were many conflicts of interest between them--Texas, for example, was big on oil, but no Republican would be foolish enough to advocate for offshore drilling in tourism-heavy Florida. Policy was made by ignoring differences rather than resolving them, and calm could be maintained as long as each faction stuck to its own territory[fn:4].

This gave Trump the opportunity to sweep in, Genghis Khan-like, and overpower the regional chiefs with the force of his personality. One by one, they fell. Jeb Bush was swept aside in the 2016 primaries and retired from political life. John McCain passed away in 2018 without a clear heir. Mitt Romney, the 2012 GOP candidate, was by 2020 [[https://www.cnn.com/2020/01/31/politics/mitt-romney-not-invited-cpac-impeachment-witness-vote/index.html][persona non grata]] at CPAC. Some former opponents, like Ted Cruz and Marco Rubio, saved their careers by aligning with Trump after having opposed him. Out of power, Trump further consolidated his grip on the party, waiting out the likes of Mitch McConnell, who announced he'd [[https://apnews.com/article/mitch-mcconnell-senate-republican-leader-stepping-down-ba478d570a4561aa7baf91a204d7e366][retire]] at the end of 2024. By the time Trump re-enters the White House in 2025, there will be no meaningful opposition to him within the GOP[fn:5].

The Democratic Party, on the other hand, is much more institutional, buttressed by layers of bureaucracy and [[https://www.brookings.edu/articles/how-super-delegates-can-do-super-damage-to-america/][party elders]] who play an outsized role in candidate selection. Obama's strong performances in '08 and '12 did not result in him taking over the party. Instead, he had to concede power to other factions every step of the way, making long-serving senator Joe Biden his VP and former First Lady Hillary Clinton his Secretary of State, later backing both for their own presidential runs. Outsiders like the "Squad" have tried, but [[https://www.newsweek.com/democrats-squad-suddenly-falling-apart-what-next-1938990][failed]], to take the party in a different direction. It seems unlikely that a political neophyte (say, [[https://www.latimes.com/california/story/2024-07-13/column-instead-of-just-criticizing-biden-maybe-george-clooney-should-take-his-place][George Clooney]]) would be able to mirror Trump's success, especially if their aim is to win back the non-college voters their current stalwarts so vehemently despise.

** Impermanent victory, ephemeral defeat

While Trump won handily, he did not win overwhelmingly. He received fewer electoral votes than Obama did, and his popular vote margin is around the same as Clinton's in 2016, an election she lost. Furthermore, this is his last term, and there are open questions as to whether the next GOP candidate (say, JD Vance) can carry this nascent coalition forward.

Even if the trend of more minorities voting Republican continues, it may well be countered by fewer whites doing the same, which cost Trump the election in 2020. Utah, a very white and very reliably Republican state, was among the few places to see a [[https://www.fox13now.com/news/politics/a-blue-trickle-against-the-red-wave-utah-may-skew-slightly-to-the-left][leftward swing]] in the 2024 election[fn:6]. The party loyalties of Hispanics and Asians are also more malleable than those of whites and blacks, and a shift back towards the Democrats in the next election is entirely possible.

What seems clear, though, is that the Republicans are further along the process of groping to a new understanding of what the party stands for: more nationalism, less free trade. The Democrats, playing defense, have been forced to [[https://www.cnn.com/2024/09/13/politics/china-tariffs-biden-trump/index.html][adopt Trump's tariffs]] and reimplement some of his [[https://www.pbs.org/newshour/politics/biden-administration-toughens-asylum-restrictions-at-border][border policies]]. Yet, this only increases their [[https://www.politico.com/news/2024/06/06/biden-border-move-infuriated-progressives-00162171][internal contradictions]]. The Big Tent is stretched [[https://www.npr.org/2024/03/06/1236201842/democrats-have-consider-their-party-to-be-a-big-tent-does-it-have-holes-in-it][past the breaking point]]; something has to give, but what?

* Footnotes

[fn:1] This is not a new phenomenon. Dwight Eisenhower's "[[https://americanhistory.si.edu/collections/object/nmah_529457][I like Ike]]" campaign is one of the most memorable in American history.

[fn:2] So have [[https://www.axios.com/2024/10/11/mark-milley-trump-fascist-bob-woodward-book][those of Trump]], but Harris wasn't running for president at the time, so there was little for disgruntled aides to gain by trashing her.

[fn:3] There are two ways to interpret the election data. One is to note that a majority of whites voted for Trump while non-whites didn't. The other is to recognize that it's the rightward shift among the latter that made the difference compared to 2020.

[fn:4] This is similar to the Democrats' coalition-building, except the divisions are geographical instead of ethnic.

[fn:5] Lisa Murkowski of Alaska won a very close Senate race in 2022 despite Trump's (and the state GOP's) [[https://www.cnn.com/2021/06/18/politics/trump-endorses-kelly-tshibaka-lisa-murkowski/index.html][endorsement of her opponent]], but Murkowski's primarily known for her [[https://www.murkowski.senate.gov/press/release/murkowski-continues-fight-against-frankenfish-moves-to-block-fda-commissioner-nominee][narrow interests]] regarding Alaska, and is unlikely to lead any type of anti-Trump crusade.

[fn:6] Many Utahns were offended by Trump's rough handling of Mitt Romney, who's basically Mormon royalty. Mormons also tend to be more [[https://religionnews.com/2014/11/21/mormon-immigration-obama/][pro-immigration]] than other religious conservatives, with Latinos among the [[https://www.axios.com/2022/08/25/latino-mormons-religion-lds-utah][fastest-growing]] LDS populations.
