#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: No children of men
excerpt: What is the cause of low and declining fertility?
---
#+END_EXPORT

The decline of global fertility has been a persistent phenomenon for several decades, yet every once in a while media loves to make new hay about it. In 2014 we saw stories about how South Koreans would become [[https://www.nbcnews.com/news/asian-america/could-south-koreas-low-birth-rate-really-mean-extinction-n190151][extinct by 2750]] if low fertility trends continued[fn:1], while in 2022 Elon Musk's [[https://www.cbsnews.com/news/elon-musk-japan-low-birth-rate/][tweet]] about Japan "disappearing" proved to be irresistible headline fodder. Action must be taken /today/, we are told, to prevent disaster generations from now[fn:2]. Borders need to be [[https://www.businessinsider.com/us-population-decline-worker-shortage-labor-birth-rates-immigration-economy-2023-5][thrown open]] and [[https://www.axios.com/2024/01/29/ai-jobs-world-companies-labor-shortage][AI must be embraced]] to avoid crippling labor shortages, while [[https://www.wionews.com/world/japan-witnesses-baby-boom-after-this-company-banned-late-night-work-heres-what-happened-616738][working hours]] and [[https://www.cnn.com/2023/03/26/asia/japan-paternity-leave-policy-challenges-intl-hnk-dst/index.html][parental leave]] need to be overhauled so people actually have time to have children. Each advocate for a "solution" claims to know the "true" cause of low fertility, from toxic corporate culture to gender discrimination. Yet, is this supported by the facts? What do we /actually/ know from the empirical data?

** Stones rolling downhill

One thing we know about fertility decline is that it's a global phenomenon. US fertility rate in 1970 was 2.48; in 2021, it was 1.66. Chinese fertility in 1970 was 6.08; in 2021, it was 1.16. Kenyan fertility rate in 1970 was 8.02; by 2021, it was down to 3.34. Across countries and continents, fertility falls inexorably. [[https://www.ined.fr/en/publications/editions/population-and-societies/mapping-the-massive-global-fertility-decline-over-the-last-20-years/][Two thirds of the world]] now live in areas with fertility below the replacement rate of 2.1.

Not only is fertility falling, but it's doing so much faster than predicted. In 2016 the Korean statistical agency predicted that population would [[https://asia.nikkei.com/Spotlight/Comment/East-Asia-faces-population-drop-10-years-earlier-than-anticipated][start shrinking in 2032]]; it actually did so in 2020. It's a similar story for Taiwan, whose population [[https://www.france24.com/en/live-news/20210108-taiwan-population-fell-for-first-time-in-2020][started falling the same year]] and has continued to do so since. Turkish fertility [[https://turkishminute.com/2024/05/16/turkey-records-dramatic-decline-its-fertility-rate-official-data/#:~:text=According%20to%20the%20Turkstat%20data,of%202.1%20children%20per%20woman.][fell to 1.51 in 2023]], while Argentina, long one of the most fertile Latin American countries, saw a [[https://www.batimes.com.ar/news/argentina/average-argentine-woman-now-gives-birth-to-less-than-two-children.phtml][rate of only 1.55]] in 2020. African fertility rates, which remain high in comparison, have fallen from 7's and 8's to 3's and 4's, with more developed countries like South Africa and Botswana hovering in the low 2's.

One reason projections even a few years out end up way off is that they tend to assume fertility has reached a nadir and will persist or even rebound. The 2750 number for South Korean extinction is ridiculous not only because it tries to predict something seven centuries in the future, but that it assumed the then record-low rate of 1.19 couldn't fall any further. A decade later, South Korean [[https://time.com/6835865/south-korea-fertility-rate-2023-record-low/][fertility is 0.72]], the lowest in the world, with no sign of bottoming out. Sometimes countries do see a period of rebound, as with Japan in the late 2000's, but this [[https://www.investopedia.com/terms/d/deadcatbounce.asp][dead cat bounce]] provides only false optimism before fertility resumes its [[https://asia.nikkei.com/Spotlight/Society/Japan-s-fertility-rate-sank-to-record-low-in-2023-estimate#:~:text=TOKYO%20%2D%2D%20Japan's%20fertility%20rate,decline%20outpacing%20the%20government%20forecast.][steady downward march]].

** Land of the setting sons

Though lower fertility is a global phenomenon, East Asia stands apart in both the speed with which rates have declined and the depths to which they've fallen. [[https://data.worldbank.org/indicator/SP.DYN.TFRT.IN?most_recent_value_desc=false][World Bank data]] from 2022 shows that the lowest fertility of any jurisdiction is Hong Kong, at 0.7. Singapore and Macao are at 1.0 and 1.1, respectively, while China's at 1.2. Japan, long the poster child for low fertility, is actually the highest at 1.3. Taiwan, excluded for political reasons, is just above Korea. Even in North Korea, Comrade Kim Jong-un was seen on state TV [[https://www.newsweek.com/north-korea-kim-jong-un-cries-while-urging-mothers-have-more-children-1849871][crying]] over the country's lack of newborns.

These are extraordinarily low numbers--not just below replacement, but in some cases less than half and still falling. South Korea's [[https://www.populationpyramid.net/republic-of-korea/2023/][population pyramid]] looks like a top balanced on its tip, at risk of falling over any second. The labor force is expected to [[https://www.koreaherald.com/view.php?ud=20240506050102][shrink by a quarter]] over the next two decades (recall that such projections tend to be optimistic). The generation currently entering the workforce is half the size of the one exiting it, while the next generation is half the size again.

So what is it about East Asia that has sent its fertility off a cliff? We'll get to this question later, but first we should address what /aren't/ the causes of the region's demographic gap.

There have long been arguments for country-specific factors, such as China's [[https://foreignpolicy.com/2021/11/04/china-one-child-policy-fertility-rates/][One-Child Policy]], in causing low fertility, yet these claims are laughably easy to disprove. The big decline in Chinese fertility was [[https://www.economist.com/china/2024/03/21/chinas-low-fertility-trap][in the 1970's]], which saw the rate tumble from around 6 to 2.7. The One-Child Policy was not implemented until 1980, and even then took a few years to really get going. And the [[https://www.brookings.edu/articles/the-end-of-chinas-one-child-policy/][lifting of the policy in 2016]] has not led to a baby boom; quite the opposite, in fact, as fertility continues to decline despite the government's [[https://www.bbc.com/news/world-asia-china-58277473][increasingly shrill demands]] that it increase.

Other country-specific claims include Japanese women's [[https://www.asahi.com/ajw/articles/15011110][housework burden]], South Korea's [[https://www.nytimes.com/2023/01/27/opinion/south-korea-fertility-rate-feminism.html][feminist movement]], and Taiwan's [[https://globaltaiwan.org/2023/08/taiwans-graying-economy-challenges-its-growth-prospects/][wage stagnation]]. Yet none of these is satisfactory in explaining the region as a whole. Furthermore, most of these are existing issues. Japanese women certainly had to do more housework back when they had more children--not least because taking care of those children was itself work. Just because something is a problem does not mean it's the cause of other problems. When trying to explain differences, we need look at deltas--what actually changed, not merely what we wish would go away.

** Twenty bucks or twenty lashes?

A number of countries have tried to use government policy to reverse the trend. These typically revolve around more generous [[https://www.mercer.com/en-us/insights/law-and-policy/japan-expands-child-care-leave-entitlement/][parental leave]] and [[https://www.koreaherald.com/view.php?ud=20231218000708][child subsidies]], though poorer countries have tried to offer gimmicks like [[https://www.huffpost.com/entry/make-a-baby-win-an-suv_b_63225][televisions and SUVs]]. In recent years, greater desperation has led to more aggressive measures, such as forcing real estate developers to set aside [[https://www.koreaherald.com/view.php?ud=20240325050714][housing for new parents]] or [[https://www.businessinsider.com/hungary-income-tax-new-moms-encourage-women-children-birth-rates-2023-1][eliminating taxes for young mothers]]. Some cities have even turned to playing matchmaker, with Tokyo launching a [[https://www.newsweek.com/japan-launches-dating-app-boost-birth-rate-1908872][dating app]] and Tainan, Taiwan setting up [[https://www.latimes.com/world-nation/story/2023-10-24/taiwan-government-matchmaker-plummeting-birth-rate][blind dates]].

All of these measures have been abject failures. In most countries that have tried them, like South Korea, fertility has declined at an accelerating pace. In others, like Hungary, fertility has ticked up, for which the government is quick to claim credit, yet no causal relationship has been proven[fn:3]. In fact, there's not a single modern case of a country going from below replacement rate to back above. Does this mean there's nothing governments can do to get people to have more children?

Perhaps that's too pessimistic. There's at least one major instance of the State successfully increasing fertility. In the late 1960's, Romanian leader Nicolae Ceaușescu decided Romania should have 30 million people instead of 20, and issued [[https://en.wikipedia.org/wiki/Decree_770][Decree 770]], which heavily restricted contraception and abortion. Women were monitored monthly by gynecologists, and those deemed skirting their patriotic duty of having children were denied opportunities for work and housing[fn:4]. The result was an immediate doubling of the birth rate and the biggest generation in Romanian history.

Such "success", however, was short-lived. Wealthier individuals[fn:5] were able to acquire contraception on the black market, while poorer households sought out illicit abortions. After Ceaușescu [[https://en.wikipedia.org/wiki/Romanian_revolution][left office via machine gun]] in 1989, fertility plunged, and Romania today has about the same population as when the decree was issued.

** Breaking down the pipeline

The failure of repeated government intervention, even of the most forceful kind, raises a basic question: what actually causes low fertility?

Since, as mentioned, there are /zero/ examples of countries going from below replacement to above in a sustained matter, this section is necessarily speculative. But some things can still be learned by following data and applying logic, so long as we avoid going on ideological tangents[fn:6].

The first fact is that, for many, having children is something that only occurs after marriage. The extent to which this is true varies greatly by country. The OECD average for births to unmarried mothers is [[https://www.oecd.org/els/family/SF_2_4_Share_births_outside_marriage.pdf][over 40%]], but this ranges from 75% in Chile to 2% in Japan.

Here we get our first hint as to why East Asian fertility rates are particularly low. As the [[https://asia.nikkei.com/Spotlight/Society/Japan-heads-for-marriage-ice-age-with-lowest-number-in-90-years2][number of marriages declines]], so does the number of children--in fact, almost the /entire/ drop in fertility in countries like South Korea and Japan can be explained by fewer marriages. Policies encouraging those who are already married to have more children, such as by [[https://www.businessinsider.com/south-korea-pay-reverse-vasectomy-tubal-ligation-birth-rates-low-2024-5][reversing vasectomies]], are barking up the wrong tree [[https://www.cnn.com/2022/12/03/asia/south-korea-worlds-lowest-fertility-rate-intl-hnk-dst/index.html][at great cost]]. Yet it seems to be all governments /can/ do, because they have no idea how to get people to say "/I/ do"[fn:7].

But let's take a step back. Before people get married, they have to be in a relationship. The old days of arranged marriages, where bride and groom saw each other for the first time at the wedding, are long gone[fn:8]. An increasing share of people, however, are [[https://www.koreaherald.com/view.php?ud=20240104000686][living alone]]. A third of Japanese between 20 and 49 report [[https://www.nippon.com/en/japan-data/h01864/][never having dated]], and 60% identify as "[[https://www.npr.org/2009/11/25/120696816/in-japan-herbivore-boys-subvert-ideas-of-manhood][herbivore men]]" who are reluctant to initiate relationships. It's hard to find any research about women's attitudes towards such "sensitive" men, but [[https://www.youtube.com/watch?v=K305Mo0slmo][anecdotally]] they aren't viewed highly as marriage material.

Why aren't more people pursuing relationships? According to [[https://link.springer.com/article/10.1007/s12110-022-09422-2][both sexes]], money is the leading problem. Of all the ways in which gender roles have become equitable, finances are a laggard. Even among Gen Z, [[https://www.nytimes.com/2024/02/10/business/gen-z-dating-pay-etiquette.html][over half of women]] expect men to pay for dates, and there was no difference among study participants' self-reported views on gender[fn:9]. Comparisons between unmarried women and similar married ones suggest that hypothetical husbands would make [[https://www.psychologytoday.com/us/blog/meet-catch-and-keep/201909/do-women-face-a-shortage-of-men-worth-marrying][55% more money]] than the men actually available. Since everyone agrees that a man who earns less than a woman is an [[https://www.cnn.com/2017/09/28/health/american-men-less-marriageable-partner/index.html][undesirable marriage partner]], this is a serious barrier to getting more couples to tie the knot.

Now we get another clue as to why East Asians are particularly impacted. Across the region, men are expected to purchase a house before marriage[fn:10]. With an average home price-to-income [[https://www.koreatimes.co.kr/www/biz/2024/06/602_359208.html][ratio of 26]], it's no wonder that Koreans are having trouble walking down the aisle. [[https://english.hani.co.kr/arti/english_edition/e_business/1122087][Barely an eighth]] of those 34 and under own homes, and the situation is desperate enough that half of married couples [[https://english.hani.co.kr/arti/english_edition/e_business/1122087][continue to rent]]. The average age of first time [[https://www.koreaherald.com/view.php?ud=20190624000728][home ownership is 43]], rising to 57 among the bottom 40%[fn:11]. Citing lack of money, the proportion of young South Koreans with a positive attitude towards marriage fell from [[https://www.cnn.com/2023/08/29/asia/south-korea-marriage-kids-kostat-survey-intl-hnk/index.html][56% to 36%]] over the past decade. Furthermore, the results are highly gender-skewed, with only 28% of women viewing marriage positively.

Working backwards, we see a complete breakdown of the pipeline from dating to marriage to having children. This cannot be solved by tweaking childcare subsidies. The wholesale socio-economic reforms necessary to upend this situation is far beyond any government's ability to impose.

** (No) Children of men

What can we take away from all this?

First, fertility is declining around the world at an increasing rate. Second, policies to reverse low fertility have been failures. Third, low fertility is primarily explained by fewer marriages. And fourth, falling marriage rates is probably best explained by the mismatch between women and "fit" men.

This leads to some contrarian conclusions. Closing the gender wage gap may lead to more household income for married couples[fn:12], and therefore more children. But absent a drastic change in women's expectations for significant others, it will cut the number of marriages[fn:13]. The net effect on fertility depends on which is the greater force. My money's on the latter, which would mean more income equality leads to /fewer/ children, not more. This does not imply that gender equity is bad--it simply means we had better stop touting it as the solution to the baby bust.

One nice thing about demographics is that we can predict things a long way out--although not quite 700 years. The number of 30-year-olds thirty years from now has already been determined today. Whatever population problems countries have, they had better learn to live with them, because there's nothing to be done with the next generation, and generations after that are unlikely to be primarily shaped by decisions we make today. This may just be a problem without any viable solution, except to hope that nature finds a way.

* Footnotes

[fn:1] Though surely we'll have uncovered the secret to [[https://time.com/6315607/bryan-johnsons-quest-for-immortality/][immortality]] by then?

[fn:2] As with all pet problems of the elite, the consequences of these actions are far enough removed such that those who support them won't face scrutiny for the outcome.

[fn:3] Neighboring Czechia, for instance, has also seen a fertility bump, even though it hasn't imposed the same pro-natal measures.

[fn:4] Work and housing were entirely controlled by the Party, so such threats had teeth.

[fn:5] No one loves money like Communists, and status is never more important than in a classless society.

[fn:6] Too many discussions of fertility are actually Trojan horses for feminist screeds. While women's rights is a worthwhile cause, fertility is a numbers game. Were we serious about learning from "the best", we'd be studying Niger, not Finland.

[fn:7] Dating apps and blind dates may indicate that governments are starting to recognizing the problem, but they've yet to prove to be the right solutions. Such piecemeal efforts have attracted [[https://www.reuters.com/world/asia-pacific/south-korean-city-turns-matchmaking-boost-low-birth-rates-2023-11-27/][hundreds at best]], would be expensive to scale, and have no indication of producing lasting relationships, let alone children.

[fn:8] Though [[https://koreajoongangdaily.joins.com/2023/07/01/business/economy/matchmaking-online-dating-blind-date/20230701070031726.html][matchmaking services are booming]], hardly anyone these days will sign a marriage contract without personally assessing the other party first.

[fn:9] In fact, "progressive" women were quick to cite factors like the gender wage gap as reasons men should pay, regardless of the pair's /actual/ incomes.

[fn:10] In some places, like China, a house is [[https://www.speakingofchina.com/china-articles/marriage-in-china-home-car-money/][not enough]]. Car and cash (sometimes in the form of jewelry) had better be present as well.

[fn:11] These are the people whose parents aren't able to help out. They have at most two wallets to rely on, rather than [[https://www.bjreview.com/Lifestyle/201805/t20180518_800129938.html][six]].

[fn:12] This is far from a guarantee. Absent a change in household share of GDP, it'd simply mean women earn more and men earn less.

[fn:13] Studies of [[https://www.theatlantic.com/ideas/archive/2023/03/money-wealth-lottery-impact-fertility-rate/673549/][lottery winners]] shows that "men seem to use their newfound resources to build families, while women use them to exit families".
