#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: All the wrong numbers
excerpt: Economic data often give false impressions
---
#+END_EXPORT

One commonly cited reason for the Democrats' defeat in the latest election is [[https://www.washingtonpost.com/politics/2024/11/20/why-harris-lost-democrats-lessons/][the poor economy]]. In the lead-up to the vote, [[https://news.gallup.com/poll/651719/economy-important-issue-2024-presidential-vote.aspx][90% of voters]] rated candidates' economic positions as "very important" or "extremely important", and Trump won [[https://www.wsj.com/economy/economy-election-trump-voters-c4c2e9a3][60% of voters]] who cited it as their top issue. Media's claims that the US economy was the [[https://www.msnbc.com/rachel-maddow-show/maddowblog/robust-us-economy-leaving-rich-countries-dust-rcna177130][envy of the world]] came across to many as gaslighting at a time when [[https://www.pewresearch.org/politics/2024/05/23/views-of-the-nations-economy-may-2024/][fewer than a quarter]] of Americans rated it as decent, and implorations that newspapers try harder to [[https://www.thenation.com/article/economy/debate-economy-bad-media/][spread the good news]] could only be viewed as more partisan hackery after their blatant lying to [[https://www.cnn.com/2024/06/06/media/wall-street-journal-biden-mental-acuity/index.html][defend Biden's mental acuity]].

Yet, economists can cite a bevy of data to suggest that the economy /was/ doing well. Inflation had mostly [[https://abcnews.go.com/Business/inflation-largely-back-normal-experts/story?id=114715014][returned to normal]], unemployment was at [[https://www.commerce.gov/news/blog/2023/02/news-unemployment-its-lowest-level-54-years][record lows]], and wages [[https://www.cnbc.com/2023/03/30/low-wage-workers-saw-tremendously-fast-wage-growth-since-2019.html][grew fastest]] among low-earners. How could the public fail to see these accomplishments?

** Food fight

The single most important expense for any household, more than rent, education, or healthcare, is food. You can live under a bridge, illiterate, in constant pain--but you've got to eat. It is such a biological imperative that our brains typically make sure we don't go a few hours without ingesting something, even if it's [[https://pmc.ncbi.nlm.nih.gov/articles/PMC6835708/][to our detriment]]. Such constant interaction creates an [[https://www.ceceliahealth.com/understanding-the-relationship-between-food-and-emotions/][emotional connection with food]] that goes far beyond the chemical. While we have been able to create [[https://en.wikipedia.org/wiki/Space_food][optimized nutrition packs]] for decades, no one in their right mind would eat like an astronaut three meals a day. Food, in short, carries a lot more weight with us than its constituent molecules suggest.

Food is also the economic sector that's been [[https://www.bls.gov/charts/consumer-price-index/consumer-price-index-by-category-line-chart.htm][hit hardest by inflation]] these past few years. While overall CPI peaked at around 9%, food inflation rose as high as 13% and stayed elevated for longer. The [[https://www.nerdwallet.com/article/finance/why-are-eggs-so-expensive][price of eggs doubled]] from 2022 to 2023, while that of [[https://investigatemidwest.org/2023/10/12/graphic-chicken-prices-continue-to-rise-costing-u-s-consumers-more-each-year/][chicken was up 34%]] from 2021. Supermarkets have tried to avoid sticker shock through "[[https://www.cbsnews.com/news/inflation-shrinkflation-skimpflation-toilet-paper-candy-cereal-lendingtree/][shrinkflation]]", i.e. reducing the quantity of product instead of raising prices, but consumers obviously [[https://www.nytimes.com/2024/03/01/business/economy/shrinkflation-groceries.html][don't think that's a good deal]].

It's not just groceries prices that have risen--the cost of dining out has skyrocketed as well. A persistent [[https://www.benefitnews.com/news/why-the-restaurant-industry-is-struggling-to-recruit-and-retain][labor shortage]] has caused [[https://www.axios.com/2023/12/07/restaurant-worker-wage-growth][pay to rise rapidly]] in the restaurant industry, while California [[https://shift.hks.harvard.edu/early-effects-of-californias-20-fast-food-minimum-wage-large-wage-increases-with-no-effects-on-hours-scheduling-or-benefits/][increased fast-food minimum wage]] to $20 / hour. The double-whammy of increased material and labor costs has resulted in [[https://restaurant.org/research-and-media/research/inflation/][27% higher menu prices]] between 2020 and 2024[fn:1]. A third of Americans say they're [[https://www.ipsos.com/en-us/americans-say-theyre-dining-out-less-heres-whos-cutting-back-most][eating out less]], which is confirmed by dining establishments reporting [[https://apnews.com/article/off-charts-food-restaurants-inflation-73cd4e72ec64695f720f4088fb80f9d1][lower traffic]].

Any government that fails to keep food affordable is asking to be overthrown. The Arab Spring protests a decade ago are widely blamed on a [[https://www.pbs.org/newshour/world/world-july-dec11-food_09-07][spike in the price of bread]]. The Chinese government maintains a [[https://www.nytimes.com/2019/10/07/business/china-strategic-pork-reserve.html][strategic pork reserve]], which it tapped to confront a [[https://www.ers.usda.gov/data-products/chart-gallery/gallery/chart-detail/?chartId=107941][doubling of prices]] between 2018 and 2021 due to [[https://www.reuters.com/graphics/CHINA-SWINEFEVER-FARMERS/010090DR0KM/][African swine fever]]. And the US Congress is obligated to pass a massive Farm Bill every five years, with the latest one expected to cost [[https://www.agriculture.senate.gov/newsroom/majority-blog/minority-analysis-the-may-2023-farm-bill-scoring-baseline][$1.5 trillion over a decade]], most of which is spent on food subsidies.

Even the Harris campaign knew that food prices were a problem. Kamala sought to look strong by demanding a ban on [[https://www.cnn.com/2024/08/16/business/harris-price-gouging-ban-inflation/index.html][price-gouging]][fn:2], but with her media allies simultaneously claiming that [[https://finance.yahoo.com/news/food-inflation-stabilizes-but-price-changes-remain-a-mixed-bag-170340784.html][food prices had stabilized]], voters weren't convinced. After all, the highest period of price increases was from 2021-23; why didn't the Biden administration take any action then? By saying she [[https://www.yahoo.com/news/nothing-comes-mind-harris-she-172100979.html][wouldn't have done anything different]], Kamala made clear she wasn't invested in solving the food problem.

** Squinting at quintiles

Trump's victory was built on the backs of [[https://www.reuters.com/world/us/trumps-return-power-fueled-by-hispanic-working-class-voter-support-2024-11-06/][working-class voters]]. Why might they have ditched the self-described party of the common man, aside from [[https://www.nytimes.com/2024/11/09/magazine/nancy-pelosi-election-interview.html][guns, God, and gays]]?

For one thing, they've felt the impact of inflation much more harshly. The bottom quintile spends a [[https://www.ers.usda.gov/data-products/chart-gallery/gallery/chart-detail/?chartId=58372][third of its income]] on food, compared to 8% for the highest fifth. And for low-earners, most spending is essential rather than discretionary--they don't decide, on a whim, to swing into a Spanish tapas restaurant for lunch. The incompressibility of their budgets means that price increases are a zero-sum game. If food costs more, they'll have to eat less, wear less, or drive less.

Aside from food, another major expense for poorer households is energy. Between 2020 to 2022, average gas prices per gallon went from less than $2 to [[https://www.eia.gov/dnav/pet/hist/LeafHandler.ashx?n=pet&s=emm_epm0_pte_nus_dpg&f=m][more than $5]]. Prices have since declined somewhat, but remain 50% higher than during Trump's term. The Biden administration recognized that energy prices were an issue with voters and made a gesture to [[https://www.whitehouse.gov/briefing-room/statements-releases/2024/01/26/fact-sheet-biden-harris-administration-announces-temporary-pause-on-pending-approvals-of-liquefied-natural-gas-exports/][ban new approvals]] of natural gas export facilities, hoping it'd lower costs. Yet the move was framed by the Democrats themselves as part of an anti-fossil fuel agenda, while voters with common sense knew that more production is necessary to bring down prices[fn:3].

The higher share of income spent by low-earners on food, fuel, and other essentials helps explain why they're mightily unhappy. If food prices go up 30%, and accounts for 30% of one's income, the overall increase is 9% of their earnings. Run the calculations for fuel, [[https://www.washingtonpost.com/business/interactive/2024/rent-average-by-county-change-rising-falling/][rent]], and other expenses, and the conclusion is invariably that they've fallen behind in real terms. Claims that [[https://www.epi.org/publication/swa-wages-2023/][higher wage growth]] among the poor has reduced income inequality conveniently ignore these different expenditure profiles, leading to devastatingly wrong conclusions about people's economic well-being.

** Belaboring labor

One of Biden's oft-repeated claims pointing a good economy is the unemployment rate, which had been [[https://www.wral.com/story/fact-check-did-biden-set-a-modern-record-for-low-unemployment-rates/20940134/][below 4%]] for "the longest stretch in 50 years in American history"[fn:4]. This being the case, why aren't people [[https://news.gallup.com/poll/652250/majority-americans-feel-worse-off-four-years-ago.aspx][feeling good]] about the economy?

An explanation may be that unemployment impacts some people, but inflation impacts everyone. A decline in the unemployment rate by one percentage point is a significant move, but it only impacts 1 in 100 workers[fn:5]. If the price of eggs doubles, however, all but the very rich will take note.

Another issue is that the unemployment rate is calculated against a denominator of people who are actively looking for work; those who have given up altogether are excluded. The latter are better captured by the [[file+sys:][labor force participation rate]], which crashed during the early pandemic and has struggled to recover throughout Biden's term[fn:6]. One contributor to lower participation has been [[https://www.stlouisfed.org/on-the-economy/2023/jun/excess-retirements-covid19-pandemic][early retirement]], especially among [[https://www.frbsf.org/research-and-insights/publications/economic-letter/2024/03/to-retire-or-keep-working-after-a-pandemic/][older white workers]] without college degrees. The participation rate for this group never returned to trend, unlike those of younger workers and non-whites.

The media attributes this to sexagenarians [[https://www.axios.com/2024/05/13/early-retirement-how-realistic-stock-market-investment][benefiting]] from an increase in asset prices and being financially comfortable enough to retire earlier, but evidence for this is scarce. For one thing, those without college degrees were more likely to work in jobs hit by shutdowns, which negatively impacted their finances. There are suggestions that they became /less/ prepared for retirement: the share of those with a retirement plan [[https://www.thirdway.org/blog/new-numbers-on-the-non-college-retirement-challenge][declined]] between 2019 and 2022.

An alternate hypothesis would be that these workers were knocked out of the workforce by Wuhan coronavirus, found it difficult to return[fn:7], and gave up altogether by taking early retirement, preferring lower Social Security benefits to no income at all. Such exits from the workforce can hardly be called "voluntary", and those whose careers ended on such a sour note are unlikely to give credit to the current administration.

** Grab 'em by the assets

As mentioned before, the idea that the poor have done better than the rich for the past several years due to higher income growth already has a gaping hole due to their different spending patterns. But that's small potatoes compared to a very basic fact: the rich build wealth not through labor, but through asset ownership. And boy, have assets done /very/ well!

The S&P 500, for example, is [[https://finance.yahoo.com/quote/%5EGSPC/][up 90%]] over the past 5 years. Since the wealthiest 10% of Americans [[https://finance.yahoo.com/news/wealthiest-10-americans-own-93-033623827.html][own over 90%]] of stocks, they've capture nearly all of that value. The bottom 50%, meanwhile, hold only 1% of stocks. Fewer than 60% of households own any stocks at all.

Real estate prices have also skyrocketed, with the median price of a single-family home in California rising from under $600K in 2019 to [[https://www.costar.com/article/277028088/california-home-prices-are-set-to-exceed-900000-heres-what-local-real-estate-agents-expect][nearly $900K]] by 2024. While the middle class has its wealth mostly in housing, and thus are theoretical beneficiaries of this, they're not actually gaining a single dollar unless they sell their home and move to a cheaper locale[fn:8]. For those staying put, the only likely impact they'll see is higher property taxes.

For those who don't own assets, such "wealth creation" is all downside. Aspiring homeowners simply can't save enough to even work towards a down payment. And even if they can put up the 20%, they may not be able to afford the expensive mortgages, courtesy of higher interest rates. Furthermore, higher real estate prices will translate into higher rent, which will eat up their savings even further. For these folks, it's not possible to [[https://en.wikipedia.org/wiki/Red_Queen%27s_race][run even to stay in the same place]].

Equity and housing aren't the only assets that are booming. The popularity of cryptocurrencies has exploded since the pandemic, accompanied by inevitable [[https://apnews.com/article/ftx-bankruptcy-binance-timeline-c519d50b9059aa8bff0ce8b6cd26c40e][fraud]]. The rise of such "alternative investments" is driven by a perception that traditional assets are out-of-reach, i.e. "rigged", and that the only way to catch up is by taking big, unconventional risks. When these marginal investments go bust, leaving investors in ruin, their faith in institutions only collapses further.

** Anti-social social scientists

It's popular these days for economists to claim legitimacy by being "data-driven". Hardly any paper will be accepted for publishing without a gamut of numerical analyses[fn:9]. Yet, for all their sophisticated formulas, experts fail over and over again in their predictions on public attitudes and political outcomes. Why?

Ask the average person what the difference is between finance and economics, and they'll struggle to give a clear answer. Unfortunately, economists today seem similarly confused. Finance is impersonal--it's about distilling everything down to dollars and cents so it can be compared and traded. Economics, on the other hand, is a social science--the focus is supposed to be on how people behave in response to things like changes in prices, not merely the prices themselves. For Wall Street, numbers like inflation and unemployment are just inputs into data models guiding next quarter's profits. Economists are supposed to dig deeper and figure out why these things are occurring, and to whom.

Modern economists use math to give themselves a veneer of respectability, like 19th century doctors who put on [[https://sites.utexas.edu/discovery/2022/08/30/why-do-doctors-wear-white-coats/][white lab coats]] to appear more "scientific". In doing so, they've become increasingly detached from the very people whom they're supposed to be studying. The bigger their data sets, the less they care to observe the things that actually matter to the public. Economists who wish to be socially relevant would do well to [[https://go.discovery.com/show/dirty-jobs-discovery-atve-us][spend some time with their subjects]], checking their models against personal experience, lest they lose themselves completely in fanciful yet utterly irrelevant charts.

* Footnotes

[fn:1] Even McDonald's, that low-end staple, has seen a [[https://www.cnbc.com/2024/05/29/mcdonalds-cost-increases.html][40% price increase]] since 2019.

[fn:2] Imposing prices via government diktat is a classic [[https://www.hurriyetdailynews.com/erdogan-vows-to-fight-against-exorbitant-food-prices-193536][strongman move]], yet none of the newspapers, curiously, called Harris an autocrat.

[fn:3] Oil production reached a [[https://www.eenews.net/articles/what-bidens-oil-record-means-for-the-industrys-future/][record]] under Biden, despite (mostly symbolic) [[https://www.cnn.com/2024/11/07/climate/anwr-drilling-trump-biden/index.html][moves]] to appease climate change activists. This left the administration a target of criticism from all sides.

[fn:4] While true, there was a [[https://www.factcheck.org/2023/08/biden-cherry-picks-unemployment-record/][similar stretch]] of low unemployment under Trump.

[fn:5] Maybe 3 in 100 if family are included.

[fn:6] Notably, the participation rate broke its trend of long-term decline under Trump, even increasing slightly.

[fn:7] Perhaps because they'd already been replaced by the [[https://www.washingtonpost.com/immigration/2024/02/11/trump-biden-immigration-border-compared/][millions of illegal aliens]] the Biden administration welcomed into the country.

[fn:8] An associate of mine took out a home equity loan against her higher-valued abode and invested in the stock market, generating a nice windfall. Most, however, are not this clever.

[fn:9] Whether the statistical methods are used appropriately and correctly is another matter.
