#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: Better angels of our tariffs
excerpt: The peculiar demonization a mundane economic tool
---
#+END_EXPORT

President Trump's recent [[https://x.com/realDonaldTrump/status/1885821495080825305][announcement]] of 25% tariffs on Canada and Mexico (and 10% additional levies on China) has set off apoplectic reactions from the financial press. The Wall Street Journal blasted the "[[https://www.wsj.com/opinion/the-trump-tariff-fallout-begins-canada-mexico-vow-retaliation-economic-uncertainty-da522b44][dumbest trade war in history]]", while the Financial Times fretted about "[[https://www.ft.com/content/c26b417d-549e-49f1-9478-7c381b4ad226][cataclysmic damage]]". The Economist called them "[[https://www.economist.com/finance-and-economics/2025/02/02/trumps-brutal-tariffs-far-outstrip-any-he-has-imposed-before][brutal]]", while Bloomberg claimed they're a "[[https://www.bloomberg.com/news/features/2025-02-02/who-wins-in-a-trade-war-how-trump-tariffs-threaten-companies-us-growth][wrecking ball]]". Are tariffs really so uniquely destructive, or are they actually the "[[https://www.theguardian.com/news/audio/2024/dec/16/the-most-beautiful-word-in-the-dictionary-donald-trumps-tariff-plan-podcast][most beautiful word in the dictionary]]"?

** Old friend and foe

A **tariff** is a tax paid by an importer, with a long history dating back to [[https://taxtech.digital/2023/07/26/taxes-ancient-sumer-assyria-babylonia/][ancient Mesopotamia]]. In the United States, tariffs have been central to government's functioning since the very beginning. Alexander Hamilton's 1791 [[https://founders.archives.gov/documents/Hamilton/01-10-02-0001-0007][Report on Manufactures]] advocated for high tariffs to protect domestic industry, generate government revenue, and reduce reliance on foreign countries. For most of the 19th and early 20th centuries, the federal government depended on tariffs for the bulk of its funding and used them to shape the economy and society.

But tariffs, like any policy, are a set of trade-offs. The process of allocating benefits and costs is called politics, so we should not be surprised that tariffs, which have broad impact on wealth distribution, have always been politically controversial.

In the nation's early days, Northern manufacturers were supportive of tariffs, as they could not compete with European imports[fn:1], while Southern plantation owners, who manufactured little, opposed them. The Tariff Act of 1828 was vehemently condemned by then-Vice President John C. Calhoun of South Carolina, who invented the doctrine of [[https://billofrightsinstitute.org/essays/the-nullification-crisis][nullification]] to oppose the levies. Eventually, Southern disgust with what they viewed as excessive federal concessions to Northern interests, including on tariffs, led to war.

By the early 20th Century, the US economy was highly industrialized, with behemoths like U.S. Steel dominating their sectors. Eager to expand into global markets while avoiding foreign retaliation, big businesses began to lobby for lower tariffs. At the same time, the public was concerned about monopoly and wealth concentration, viewing tariffs as favoring manufacturers at the expense of consumers[fn:2]. The [[https://www.federalreservehistory.org/essays/banking-panics-of-the-gilded-age][Panics of 1893 and 1907]] also demonstrated the danger of relying on tariffs for government revenue, as trade violently contracts during financial crises, leaving the government purse empty just when it's most needed. Thus, the stars aligned for the [[https://constitution.congress.gov/browse/amendment-16/][16th Amendment]], swiftly followed months later by the [[https://en.wikipedia.org/wiki/Revenue_Act_of_1913][Revenue Act of 1913]], which significantly cut tariffs in favor of an income tax.

** For the greater good

The Great Depression and World War II fundamentally changed the thinking around international relations, including tariffs. The [[https://www.senate.gov/artandhistory/history/minute/Senate_Passes_Smoot_Hawley_Tariff.htm][Smoot-Hawley Tariff of 1930]] was widely viewed as having worsened the economic crisis in the United States due to other countries putting up their own barriers in response. The US, then the world's largest exporter, was disproportionately hit by the consequent decline in trade. Economic crises around the world facilitated the rise of dictators, leading to massive destruction. There was a commonly-held view that greater global coordination was necessary to prevent a repeat of the conflict.

International comity didn't last long, but the formation of post-war ideological blocs reinforced the argument for lower tariffs. As tensions between the US and USSR escalated, Washington suddenly needed to counter Soviet influence in Europe and Asia. The [[https://www.wto.org/english/docs_e/legal_e/gatt47_e.htm][General Agreement on Tariffs and Trade]] (GATT) of 1947, [[https://www.archives.gov/milestone-documents/marshall-plan][Marshall Plan]] of 1948, and [[https://www.govinfo.gov/content/pkg/STATUTE-76/pdf/STATUTE-76-Pg872.pdf][Trade Expansion Act]] of 1962 all allowed the United States to grant favorable trade terms to strategically important countries. At first the justification was to help them rebuild, but the policies continued long after, as the US needed continued cooperation throughout the Cold War.

If the United States was driven by strategic need, its allies were much more transactional. Washington's economic concessions were rarely reciprocated, with West Germany and Japan in particular maintaining high tariffs and quotas on imports of food, chemicals, machinery, and automobiles. An exasperated John F. Kennedy said[fn:3] in a 1963 National Security Council [[https://history.state.gov/historicaldocuments/frus1961-63v13/d168][meeting]]:

#+begin_quote
We must firmly oppose West Germany if it increases its agricultural production to our detriment...we cannot continue to pay for the military protection of Europe while the NATO states are not paying their fair share...the Europeans will not do anything for us simply because we have in the past helped them.
#+end_quote

As the Cold War heated up, the United States began dispensing economic favors more liberally. In 1979, Jimmy Carter signed a [[https://www.presidency.ucsb.edu/documents/proclamation-4697-agreement-trade-relations-between-the-united-states-america-and-the][trade agreement]] with China that granted the country Most Favored Nation (MFN) status[fn:4], dramatically lowering American tariffs on Chinese goods. The Reagan administration expanded economic engagement with the People's Republic, easing technology controls and even starting [[https://militarymatters.online/weapons/the-jaguar-almost-the-joint-chinese-american-battle-tank/][joint military projects]]. The Tiananmen Square Protests of 1989 curtailed this, but then something very unexpected happened.

** Giddy springtime of the bourgeoisie

In 1991, the Soviet Union collapsed under a combination of intra-party rivalry and ethnic nationalism. No one was more surprised than the Americans, who had expected to continue the Cold War /ad infinitum/. There quickly arose questions which had never been seriously considered--what to do about Ukrainian nukes, for example, or how to prevent economic chaos in Central Asia. It was quickly decided that the best way to deal with the former Communist countries was to bring them into an expanded American-led system. The US granted Russia temporary MFN status in 1992, NAFTA came into effect in 1994, and the WTO replaced GATT in 1995. Globalization was off to the races.

Not everyone was so sanguine about the future, however. In 1992, geopolitical analyst George Friedman warned about a potential [[https://www.psychologytoday.com/gb/articles/199205/irreconcilable-differences][war with Japan]], noting that, with the unifying threat of the USSR gone, friction between Tokyo and Washington would escalate. That same year, author Michael Crichton (of /Jurassic Park/ fame) published [[https://www.michaelcrichton.com/works/rising-sun/][Rising Sun]], a corporate thriller doubling as a jeremiad about the Japanese economic threat. Clearly, some weren't believers in the [[https://en.wikipedia.org/wiki/The_End_of_History_and_the_Last_Man][end of history]].

None of this worried the Clinton administration, which was riding high on a wave of prosperity brought about by the exciting new technology of the World Wide Web. A combination of higher growth, lower military spending, and entitlement reform led to four straight years of fiscal surpluses from 1998 to 2001, the first since the 1960's. Russian economic reforms had been botched, Germany was struggling with reunification, and China could barely pull itself out of abject poverty. As for Japan? Its asset bubble had burst in 1992, the very year writers like Friedman and Crichton were prognosticating doom. Nothing, least of all trade policy, bothered the world's first [[https://www.theguardian.com/theguardian/2002/apr/11/guardianweekly.guardianweekly1?utm_source=chatgpt.com][hyperpower]].

** Long in the tooth

In 2001, two things happened that proved to have significant long-term impact on the United States. The first was the 9/11 attacks, which plunged the country into two major wars. The other was China joining the WTO, which destroyed American manufacturing at an unprecedented rate. The two were interrelated in that, focused on the War on Terror, the Bush administration emphasized cooperation with China, sidestepping issues like job losses and IP theft. US trade and budget deficits exploded, but the information sector was on the upswing, and federal debt was still manageable. The giddy bourgeoisie still had room to run.

The 2008 financial crisis swiftly crushed such delusions. The media narrative focused on the greedy bankers and irresponsible regulators, but bankers are always greedy and regulators always irresponsible. What led to the crisis was something structural--a global economic imbalance that had been building for years.

As countries like China, Germany, and Japan boosted their manufacturing sectors by running persistent trade surpluses, they needed somewhere to park the dollars their exporters earned. Since only American financial markets could accommodate such huge sums of money, voluminous amounts of capital began flowing into the United States. As there simply wasn't so much capital demand in the country, especially that which its own investors couldn't meet, Wall Street had to invent new assets for foreigners to buy. Collateralized Debt Obligations (CDOs) involving subprime mortgages were just one "creative" instrument to meet these needs[fn:5]. As is often said about the drug trade: where there is demand, there will be supply.

It [[https://press.princeton.edu/books/paperback/9780691163628/the-great-rebalancing][should have been clear]] by now that the post-WWII economic model, which relied on the United States to be the "consumer of last resort" for other countries' industrial output, was unsustainable. What had been a "temporary" plan to help allies rebuild had morphed into an ongoing incentive for doing American bidding during the Cold War, but now it was open season to see who could dump the most product into the US market. As long as a country was willing to repress its workers' wages and manipulate its currency against the dollar, it could gain a "competitive advantage". No one was better at this race to the bottom than China, whose centralized one-party state could keep its [[https://www.project-syndicate.org/commentary/china-household-consumption-expenditure-is-probably-higher-than-official-figures-by-zhang-jun-2024-07][household share of GDP]] at the lowest rate of any major economy in history. Something needed to change.

** Delayed rectification

The historic election of Barack Obama in 2008 caught everyone by surprise[fn:6]. With "Change!" as a slogan, he easily stormed to victory over the thoroughly discredited GOP. One would have thought that, given his youth, ethnicity, and enormous voter mandate, he would have brought profound change to the nation's economic system. Yet, that was not to be.

Obama proved to be a cautious politician, never straying too far from the status quo. No radical economic reform was on the table. Instead, he dutifully signed free trade deals with Korea, Colombia, and Panama. Obama also began negotiating the [[https://obamawhitehouse.archives.gov/issues/economy/trade][Trans-Pacific Partnership]] (TPP), which would have formed a massive trade bloc of Pacific countries.

While the 2009 recession depressed American consumer demand for a time, and subsequent quantitative easing (QE) lowered the value of the dollar, the trade deficit began growing again in 2010, with the goods shortfall reaching $750 billion a year by the end of Obama's time in office. While Chinese surpluses continued to grow, the EU also became a big problem.

In the 2000's, southern European countries had been the dumping ground for excess industrial production from northern Europe (particularly Germany), which recycled euros back into these countries in the form of cheap loans, fueling an asset bubble[fn:7]. In 2011, these countries ran into serious financial trouble, with the likes of Greece and Ireland receiving large bailouts from the European Central Bank (ECB). As a condition for aid, they were required to impose various forms of austerity. This effectively suppressed demand and turned these countries into net exporters, sending the EU's surplus soaring--and America's trade deficit skyrocketing with it.

In the end, Obama was not the man to address the global economic imbalances that had brought about the financial crisis. Far from being the herald of a new era, he proved to be the swan song of the old, and his failure to address critical issues would lead to the rise of a very different type of politician.

** Rise of the Tariff Man

The earthquake [[https://www.tianxiangxiong.com/2017/01/28/the-rerise-of-nationalism.html][election]] of Donald Trump in 2016, the Wuhan coronavirus [[https://www.tianxiangxiong.com/2020/03/29/coronavirus-and-globalism.html][pandemic]] of 2020, the [[https://www.tianxiangxiong.com/2024/11/15/the-price-of-incoherence.html][political bankruptcy]] of the Democrats under Joe Biden, and Trump's stunning return in 2024 are relatively recent events that don't merit recounting. What is worth studying, however, is how Trump has brought tariffs back into the mainstream, and how his use of them has served--or not served--American interests.

The first thing to note is that Trump is not alone in levying tariffs, even in the globalization period. Bush had ordered them on [[https://ustr.gov/archive/Trade_Sectors/Manufacturing/Steel/Section_Index.html][steel]], and Obama slapped them on Chinese [[https://www.nbcnews.com/id/wbna32808731][tires]]. Then, as now, analysts [[https://www.piie.com/publications/policy-briefs/us-tire-tariffs-saving-few-jobs-high-cost][blasted]] the protectionism, claiming it "cost American jobs". But Trump's 2018 tariffs on China were by far the most wide-ranging in modern history, covering over $360 billion in goods. And by embracing tariffs whole-heartedly rather than reluctantly acknowledging that they're a necessary evil, he completely changed the conversation on trade[fn:8].

But Trump, true to his /Art of the Deal/ persona, is more interested in using tariffs as a negotiating cudgel than as principled policy. Soon after announcing tariffs on Canada and Mexico, Trump declared he was [[https://apnews.com/article/trump-tariffs-canada-mexico-china-sheinbaum-trudeau-017efa8c3343b8d2a9444f7e65356ae9][suspending]] them as the two countries made a show of stepping up border enforcement. While he has mused about using [[https://www.fox5dc.com/news/trump-proposes-abolishment-federal-income-tax][tariffs to replace the income tax]], thereby reverting the past century of post-16th Amendment practice, there's little indication they will be levied high enough, broad enough, and for sufficient duration to take a meaningful step in this direction.

But even if Trump were serious about tariffs, the bilateral sort he favors is [[https://carnegieendowment.org/china-financial-markets/2021/01/how-trumps-tariffs-really-affected-the-us-job-market][not every effective]] in addressing global imbalances. While US-China trade fell after 2018, US-Vietnam trade rose, and China-Vietnam trade rose by almost exactly as much. This strongly suggests that Chinese firms have been using Vietnam to [[https://fulcrum.sg/vietnam-china-and-rerouting-when-perceptions-matter-as-much-as-reality/][transship]] product to the United States[fn:9]. Other loopholes, like the /de minimis/ rule, allowed Chinese firms like Pinduoduo (parent of low-cost retailer Temu) to avoid tariffs by shipping small packages [[https://www.pymnts.com/news/ecommerce/2025/trumps-tariffs-to-eliminate-de-minimis-exemption-on-small-packages/][directly to American households]].

Trump's opponents argue that, even if applied as intended, tariffs are bad because all the cost will be [[https://www.nytimes.com/2025/02/02/business/economy/trump-tariffs-what-to-know.html][borne by the consumer]]. This is clearly nonsense. There are several possibilities for dealing with tariffs, depending on who has leverage. The importer could force the exporter to eat the cost, consumers could force the importer to eat the cost, importers could pass the cost onto consumers, and the exporter's government could manipulate its currency to offset some of the pain. In practice, a combination of all of these tends to happen.

But suppose that, instead of bilateral tariffs, a more ambitious [[https://www.bloomberg.com/news/articles/2025-01-27/trump-vows-near-future-tariffs-calls-deepseek-progress-good][universal tariff]] was imposed. Would this be effective in reducing the American trade deficit?

** Two sides of the same coin

Basic international accounting says that a nation's balance of payments involves two accounts, the [[https://www.investopedia.com/ask/answers/031615/whats-difference-between-current-account-and-capital-account.asp][current and the capital]]. Trade in goods and services shows up in the current account, while financial flows show up in the capital account. It is a mathematical necessity that these two must balance, but the math doesn't imply anything about which drives the other.

Michael Pettis of Peking University has long noted the [[https://carnegieendowment.org/china-financial-markets/2020/12/foreign-saving-gluts-and-american-financial-imbalances?lang=en][failure]] of economists and policymakers to grasp this key point. The "mainstream" narrative is something like this: Americans save too little and consume too much, so the United States must borrow a lot of money from foreigners to pay for imports. We had better be [[https://www.cbsnews.com/news/clinton-to-china-keep-buying-our-debt/][grateful to the foreigners]], because if they stop lending us money, we'd be in big trouble[fn:10]. And we must be /especially/ careful to [[https://thehill.com/business/5118693-trump-threats-tariffs-brics-reserve-currency/][maintain the dollar's role]] as the global reserve currency, because if others "lose confidence" in the dollar, they'll switch to something else and bring financial calamity unto Americans.

The remarkable thing about this thinking is how it's perfectly opposed to the truth. The claim is, in short, that our current account deficit demands a capital account surplus, whereas the reality is that our capital account surplus forces a current account deficit. Aggressively mercantilist exporters, such as China and Germany, have socio-political reasons for building industrial bases far larger than their domestic markets can support[fn:11]. That product needs to go somewhere, and the United States is the [[https://www.eiu.com/n/a-closer-look-at-the-global-trade-landscape/][biggest sucker]] in the neighborhood. The dollar's unique role only exacerbates this, as it means the Federal Reserve does not stop foreigners from recycling their dollars into American assets as much as they want[fn:12], thereby perpetuating this unsustainable process.

Foreign capital flows benefit Wall Street, which takes a cut every time money moves, but damage the broader public. When poured into real estate, they make housing less affordable. When pumped into the stock market, they inflate bubbles and widen income inequality. When rushing into farmland, they pile pressure on small farmers, which translates into higher food prices. And, most universally, they strengthen the value of the dollar, making American exports uncompetitive and crushing domestic industry.

A universal tariff would reverse this process by forcing down the current account deficit and therefore the capital account surplus. But taxing /all/ imported goods will, in the short run, fuel inflation. It would also be difficult to police, encouraging [[https://www.ice.gov/news/releases/hsi-los-angeles-special-agents-arrest-8-customs-fraud-scheme-involving-goods-china][smuggling]]. The fundamental issue is that it attacks the problem from the wrong end. What began with excess capital must be solved there.

** Chopping at the roots

In 2019, Missouri Republican Josh Hawley and Wisconsin Democrat Tammy Baldwin introduced a [[https://www.baldwin.senate.gov/news/press-releases/competitive-dollar-for-jobs-and-prosperity-act][proposal]] to tax capital inflows via a "market access charge" for foreign purchases of American assets. Such a tax directly addresses excess foreign capital inflows without having the government police every business transaction, and is a much smarter approach to dealing with the trade deficit.

While the proposal didn't make it out of the Senate Banking Committee, opponents have felt the need to [[https://www.cato.org/policy-analysis/trade-investment-are-not-balancing-act][condemn]] it [[https://www.project-syndicate.org/commentary/capital-inflow-tax-to-cut-us-trade-deficit-would-be-a-disaster-by-maurice-obstfeld-2024-06][years later]]. On the flip side, Prof. Pettis wrote in [[https://carnegieendowment.org/china-financial-markets/2019/08/washington-should-tax-capital-inflows?lang=en][support]] of the bill, noting that it

#+begin_quote
would give the United States a tool for managing trade imbalances that is far more flexible than WTO interventions, trade negotiations, tariffs, or subsidies.
#+end_quote

Opponents decry that it would stifle American businesses by depriving them of capital, but no one who's followed the Fed's experiment in ultra-low interest rates for the past 15 years can seriously defend the idea that American firms have trouble borrowing money. On the contrary, evidence is strong that there has been /too much/ capital chasing too few good investments, resulting in bad decisions and outright [[https://apnews.com/article/ftx-bankruptcy-binance-timeline-c519d50b9059aa8bff0ce8b6cd26c40e][fraud]]. In the real world, there's no such thing as "the more the better". Even water, when consumed in excess, can be [[https://www.today.com/health/news/water-intoxication-death-rcna99472][fatal]].

** Expanding horizons

Before Trump popularized them, tariffs had been considered dead relics of a forgotten age. The speed with which economic nationalism has swept the country has shocked the political class, especially those whose careers were forged in the heady 90's. Their attacks on tariffs have focused on Trump's personal shortcomings, such as his aggression and inconsistency. By associating tariffs with Trump, they hope that tariffs will go away when Trump does.

What they fail to recognize is that Trump, unlike Obama, is a transformative leader. Tweet by tweet, he moves the [[https://www.mackinac.org/OvertonWindow][Overton Window]] and uncovers new political possibilities. There's no reason to believe that a public which has shrugged off tariffs would be resistant to other forms of "radical" economic policy, such as [[https://www.elibrary.imf.org/display/book/9781589061170/ch03.xml][capital controls]] and [[https://www.freightwaves.com/news/u-s-postal-service-places-embargo-on-parcels-from-china][import bans]], which were commonplace only a few decades ago. The financial press may want to save some of their outrage--they'll need it in the years to come.

The great physicist Max Planck once [[https://en.wikipedia.org/wiki/Planck%27s_principle][quipped]] that "science advances one funeral at a time". The same might be said of politics, where those clinging to the [[file+sys:][Washington Consensus]] seem determined to be buried with it. Chuck Grassley, long-time senator from Iowa, [[https://www.thegazette.com/national-politics/sen-grassley-taking-wait-and-see-approach-to-trumps-proposed-tariffs-on-canada-mexico/][warns]] that "free-traders are [now] in a minority". He's right--but he's also 91. [[https://www.businessinsider.com/mitch-mcconnell-criticizes-trump-tariffs-2024-9][Mitch McConnell]], 82, and [[https://apnews.com/article/business-nancy-pelosi-congress-8685e82eb6d6e5b42413417f3d5d6775][Nancy Pelosi]], 84, aren't far behind. The future clearly belongs to the likes of [[https://reason.com/volokh/2024/07/15/gop-vp-nominee-j-d-vance-is-an-enemy-of-free-markets/][J.D. Vance]] and [[https://www.wesa.fm/politics-government/2024-08-27/deluzio-fetterman-make-stuff-here-policy-agenda][Chris Deluzio]], both 40, who differ much but agree on one thing: "[[https://x.com/RepDeluzio/status/1793041344589447541][no more globalist and free trade crap]]".

* Footnotes

[fn:1] The very purpose of colonies was to provide raw materials and serve as captive markets, thereby supporting jobs in the mother country. In Ben Franklin's 1751 [[https://founders.archives.gov/documents/Franklin/01-04-02-0080][Observations Concerning the Increase of Mankind]], he argued that Britain should not repress manufacturing in North America, lest it cede advantage in the New World to the Spanish and Germans. London's continued economic restrictions on the Thirteen Colonies was a major trigger of the Revolutionary War.

[fn:2] They were right, but as public opinion tends to lag economic reality, their reasoning actually brought them in alignment with, rather than opposition to, the mega-corporations they opposed.

[fn:3] A quote that could have come directly from Donald Trump, had it been posted, in all-caps, on Twitter.

[fn:4] Unreciprocated, of course, until China was forced to do so upon joining the WTO in 2001.

[fn:5] Others included Collateralized Loan Obligations (CLO), Structured Investment Vehicles (SIV), Credit Default Swaps (CDS), and more.

[fn:6] Not least of all Hillary Clinton, who will never forgive Obama for denying her a sure chance of being president in 2008.

[fn:7] The parallels with the United States should be obvious.

[fn:8] There's no better evidence for this than Biden's maintenance of all of Trump's tariffs on China and [[https://www.cnn.com/2024/09/13/politics/china-tariffs-biden-trump/index.html][addition]] of his own.

[fn:9] However, such strategies are not cost-free to China. The prices at which Chinese merchants can sell to Vietnam are far below what they could charge the United States, and that's before considering additional fees for transportation, storage, etc.

[fn:10] Think of all the children who won't be getting their Tickle-Me Elmos at Christmas!

[fn:11] These range from job creation to dominating new technologies, but the most fundamental reason is that the manufacturers are politically influential, and can force the government and public [[https://centreforpublicimpact.org/public-impact-fundamentals/the-hartz-employment-reforms-in-germany/][subsidize them]].

[fn:12] Whereas if you tried to buy a lot of Swiss assets, for example, officials in Zurich will be very cross with you.
