#+OPTIONS: toc:nil num:nil

#+BEGIN_EXPORT html
---
layout: post
title: Generating classes in Clojure
excerpt: JVM adventures await!
---
#+END_EXPORT

I rarely use the [[https://clojure.github.io/clojure/clojure.core-api.html#clojure.core/gen-class][:gen-class]] facility in Clojure, but when I do, I usually trip over one issue or another. After finally spending some time to read the [[https://clojure.org/reference/compilation][documentation]] and peruse [[https://github.com/clojure/clojure][source code]], I've got a better understanding of how it all fits together.

** Write that down, write that down!

When Clojure code is evaluated, the compiler generates JVM bytecode and loads it into memory. For various reasons, such as improved startup time, it can be advantageous to compile namespaces into actual classfiles. These compiled namespaces need to be ~:import~'ed instead of ~:require~'ed.

A namespace is normally compiled into a class ending in =__init=. For the simplest namespace:

#+begin_src clojure
  (ns clj-genclass.core)
#+end_src

We can compile with [[https://leiningen.org/][Leiningen]]:

#+begin_src sh
  lein compile clj-genclass.core
#+end_src

And see the class =core__init.class= under =target/classes/clj_genclass=.

** Lookin' fresh

The resulting class isn't very convenient to work with, however. That's where ~:gen-class~ come in: it provides a large number of options[fn:1] that make the generated class more like the Java library classes we interop with.

To automatically compile classes before starting a Lein REPL, the namespace needs to be added under [[https://codeberg.org/leiningen/leiningen/src/commit/8cda41784545bef71d1d605d739f4935c8fe4f21/sample.project.clj#L280][:aot]] in =project.clj=. Consider the following:

#+begin_src clojure
  (ns clj-genclass.MyClass
    (:gen-class
     :constructors {[String] []}
     :init init
     :state state
     :methods [[print [] void]]))

  (defn -init
    [txt]
    [[] txt])

  (defn -print
    [this]
    (println (.state this)))
#+end_src

Running =lein repl=, we see that the class is compiled:

#+begin_src sh
  $ lein repl
  Compiling clj-genclass.MyClass
  nREPL server started on port 57734 on host 127.0.0.1 - nrepl://127.0.0.1:57734
#+end_src

And can be immediately imported and used:

#+begin_src sh
  clj-genclass.core=> (import 'clj_genclass.MyClass)
  clj_genclass.MyClass

  clj-genclass.core=> (.print (MyClass. "My own class"))
  My own class
#+end_src

** The function is dead, long live the function

If we update ~MyClass~'s ~-print~ method, e.g.

#+begin_src clojure
  (defn -print
    [this]
    (println "foo" (.state this)))
#+end_src

We can see the changes take place either by compiling the class in the REPL:

#+begin_src sh
  clj-genclass.core=> (compile 'clj-genclass.MyClass)
  clj-genclass.MyClass

  clj-genclass.core> (import 'clj_genclass.MyClass)
  clj_genclass.MyClass

  clj-genclass.core> (.print (MyClass. "My own class"))
  foo My own class
#+end_src

Or just evaluating it in [[https://github.com/clojure-emacs/cider][CIDER]]. =lein compile= does /not/ work because it only writes to classfiles and doesn't load anything into memory.

** The old switcheroo

Classes in Java are loaded by instances of [[https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ClassLoader.html][ClassLoader]][fn:2]. Once an instance of ~ClassLoader~ has loaded a class, it must always [[https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-5.html#jvms-5.3.2][return what it already loaded]]. This means that it cannot reload a class whose definition has changed.

To get around this, Clojure takes advantage of the fact that a class is distinguished not just by its name but also [[https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-5.html#jvms-5.3.2][by its classloader]]. Every time a form is (re)evaluated, a [[https://github.com/clojure/clojure/blob/clojure-1.12.0/src/jvm/clojure/lang/Compiler.java#L7662][new instance]] of Clojure's own [[https://github.com/clojure/clojure/blob/clojure-1.12.0/src/jvm/clojure/lang/DynamicClassLoader.java][DynamicClassLoader]] is used. We can see this in action:

#+begin_src sh
  clj-genclass.core=> (defn foo [] "foo")
  #'clj-genclass.core/foo

  clj-genclass.core=> (.getClassLoader (.getClass foo))
  #object[clojure.lang.DynamicClassLoader 0x41f045a1 "clojure.lang.DynamicClassLoader@41f045a1"]

  clj-genclass.core=> (defn foo [] "bar")
  #'clj-genclass.core/foo

  clj-genclass.core=> (.getClassLoader (.getClass foo))
  #object[clojure.lang.DynamicClassLoader 0x32035f8f "clojure.lang.DynamicClassLoader@32035f8f"]
#+end_src

When ~foo~ was redefined, the new version was loaded by a different classloader. All instances of ~DynamicClassLoader~ share a [[https://github.com/clojure/clojure/blob/clojure-1.12.0/src/jvm/clojure/lang/DynamicClassLoader.java#L26-L27][cache]] so they can all find previously loaded classes. Classes that are no longer used (such as those that have been redefined) are eventually [[https://github.com/clojure/clojure/blob/clojure-1.12.0/src/jvm/clojure/lang/DynamicClassLoader.java#L45][removed]].

* Footnotes

[fn:1] ~:gen-class~ by itself does not compile a class--it only specifies /how/ a class should be compiled.

[fn:2] Except for the classes of the Java Runtime itself, which are loaded by a [[https://docs.oracle.com/javase/jndi/tutorial/beyond/misc/classloader.html][boostrap classloader]] written written in native code.
